### ISSUE TITLE
Errors do not contain an indicative message

### ISSUE THREAD

**Issue by nadavtsa** [rueian/rueidis#100]
Hi, it seems that upon error returned from Redis, the error message is always empty, which makes it hard to know what caused the error/failure of the operation.
An example use case (trying to run json.set command with NX flag with a key that already exists):
```go
// note that this (empty error message) happens also in DoMulti() func
command = jsonClient.B().JsonSet().Key("existing-key").Path("$").Value(rueidis.JSON(value)).Nx().Build()
if res := a.jsonClient.Do(ctx, command); res.Error() != nil {
        // handle error...
}
```

The struct returned from the res.Error() call contains an empty message:
```go
{
   type: (uint8) 95,
   string: "",
   values: nil,
   attrs: nil,
   integer: 0
}
```

Is there a way to return a more indicative error message?

Thank you :)

**Comment by nadavtsa** [comment]
this is not a real issue

**Comment by rueian** [comment]
Hi @nadavtsa, `type: (uint8) 95` indicates that it is a redis nil message. It should be implemented with error interface here: https://github.com/rueian/rueidis/blob/master/message.go#L28

You can also use `rueidis.IsRedisNil(res.Error())` to check with:
https://github.com/rueian/rueidis/blob/master/message.go#L16-L21
