### ISSUE TITLE
Need support Hooks so we have integrate with APM's like newrelic

### ISSUE THREAD

**Issue by SaikiranDaripelli** [rueian/rueidis#103]
Need support Hooks so we have integrate with APM's like newrelic.

Currently go-redis has AddHook at connection level which is tapped into by APM providers to provide support, is there any plan to support such feature?

EG: https://pkg.go.dev/github.com/newrelic/go-agent/v3/integrations/nrredis-v8

**Comment by rueian** [comment]
Hi @SaikiranDaripelli,

rueidis has OpenTelemetry integration here: https://github.com/rueian/rueidis/tree/master/rueidisotel
Is it possible to use it to integrate with APM providers?

I haven’t have though about hooks yet.

**Comment by SaikiranDaripelli** [comment]
Hi,
   I will try to integrate and see if it provides similar observability in a transaction when using with newrelic go agent. Can i plugin my own trace hook like one you shares, so that i can add code to tap into already existing newrelic transaction and add a span to extisting trace?

**Comment by rueian** [comment]
@SaikiranDaripelli,

I am going to add a `rueidishook` sub-package to the next release. That will allow you to plug your own code into `rueidis.Client` interface.

Please checkout: https://github.com/rueian/rueidis/pull/105

**Comment by SaikiranDaripelli** [comment]
Thank you

**Comment by rueian** [comment]
Hi @SaikiranDaripelli, then `rueidishook` sub-package is released in v0.0.82.

**Comment by SaikiranDaripelli** [comment]
Thank you, I will try it out this week.

**Comment by SaikiranDaripelli** [comment]
This is working as expected, thanks @rueian
