### ISSUE TITLE
Hope add future : command builder `export` and `import` 

### ISSUE THREAD

**Issue by 23233** [rueian/rueidis#106]
I'm use `Json Schema` define request , use `json` file export and import.

Hope add Export And Import or `cmds.Builder` Allow auto parse string template ? 

Thanks~

**Comment by rueian** [comment]
Hi @23233,

Could you provide an example of your json definition file?

**Comment by 23233** [comment]
Im use `Arbitrary` temporary resolve this way,
Thanks~
