### ISSUE TITLE
"context deadline exceeded" occurred in Redis Cluster Mode

### ISSUE THREAD

**Issue by dwzkit** [rueian/rueidis#107]
Use the following address in the Go code:

<img width="1576" alt="image" src="https://user-images.githubusercontent.com/41875799/197391645-3c640ac2-6303-4372-afab-65ed069fef97.png">

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/41875799/197391731-2beefa6b-d215-404f-be8a-cf8509e70b75.png">

On the CLI, the following command output is displayed:
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/41875799/197391967-a2ba0b40-a1b2-4ab6-ae20-0e46ba1a668c.png">

But in the go program I got an error: "context deadline exceeded".
<img width="1709" alt="image" src="https://user-images.githubusercontent.com/41875799/197391782-fbebf8e7-3435-4656-9a50-d0328c447a18.png">

The code is as follows:
<img width="1317" alt="image" src="https://user-images.githubusercontent.com/41875799/197391808-12051456-e3e0-46a7-a08b-186cb6d11605.png">

Redis Cluster Info as follows:
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/41875799/197392331-394bdcac-8d95-4bff-89c2-76daec070651.png">
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/41875799/197392354-68e02bff-5af1-4257-ba78-e8f328e3db79.png">

**Comment by rueian** [comment]
Hi @dwzkit,

Could you share:
1. What is the output of `CLUSTER SLOTS` from your redis-cli?
2. What is the output of `repo.db.Nodes()`?
3. What will happen if setting `ClientOption.ConnWriteTimeout` to -1?
4. How do you make redisearch work in cluster mode? Redisearch usually does not work with redis cluster.

**Comment by rueian** [comment]
From your screenshot, it looks like you have a quite complex network setup mixing all the RFC1918 internal IP address spaces. Maybe we should check if all the IPs listed in the screenshot, including the k8s svc ClusterIP, are accessible by your rueidis client first.

**Comment by dwzkit** [comment]
> Hi @dwzkit,
> 
> Could you share:
> 
> 1. What is the output of `CLUSTER SLOTS` from your redis-cli?
```
redis-cluster-production:6379> CLUSTER SLOTS
0
5460
10.11.14.237
6379
43bbe72b30ae061b274e42ebc50b423f43f7cb05

10.13.115.157
6379
98fac53dadc7ab0ce9023657cc9ef55fcb7aede9

5461
10922
10.9.214.218
6379
92a3b1195ad2cb2317bb4c0ea4aa88f2f6982bc3

10.11.14.224
6379
670777b1cbd0bbc29878f7538bf36ac1ee374b18

10923
16383
10.9.214.210
6379
6b904b0916d578ee813ec2ccb9ebb1c5ca41fd23

10.13.115.158
6379
b2a059b8b834c67ee544b7caa9091cd19d8ad7db
```
> 2. What is the output of `repo.db.Nodes()`?
```
[root@k8s-master01 node02]# kubectl logs -f -n development good-num-api-redis-cluster-5bbc4fbc6-j8tps
server started at V5.6: 2022-10-24 03:52:23.659575
2022-10-24 03:52:23	INFO	logtool/log.go:89	[NewLogger] success
env: prod
db_phone_num.Nodes() map[10.11.14.224:6379:0xc0003360f0 10.11.14.237:6379:0xc0003360a8 10.13.115.157:6379:0xc0003360c0 10.13.115.158:6379:0xc000336120 10.9.214.210:6379:0xc000336108 10.9.214.218:6379:0xc0003360d8 redis-cluster-production.redis-cluster:6379:0xc000336138]
listening on port: :8088
```
> 3. What will happen if setting `ClientOption.ConnWriteTimeout` to -1?
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/41875799/197415318-cf14c6e7-f0f0-4f10-aa5b-77eb71f6ff18.png">
There was no panic, but there was also no response:
<img width="1913" alt="image" src="https://user-images.githubusercontent.com/41875799/197415341-37580f54-9b31-40fc-9db3-cf662ecff6d3.png">

> 4. How do you make redisearch work in cluster mode? Redisearch usually does not work with redis cluster.
Step1: Build RediSearch oss module for redis-cluster mode version 
According to https://redis.io/docs/stack/search/development/, I can build a community version of the cluster mode rediSearch.so.
```
git clone -b v2.2.9 --recursive https://github.com/RediSearch/RediSearch.git
make setup
make build COORD=oss
```
module-oss.so # module-oss.so is the community version of the cluster mode rediSearch.so
Step2:Build a redis Docker include  module-oss.so(rediSearch.so) and rejson.so
```
FROM bitnami/redis-cluster:7.0.5-debian-11-r0
#将modules目录下的所有文件复制到镜像中
USER root
COPY modules /opt/bitnami/redis/modules
#给/opt/bitnami/redis/modules下的所有文件赋予可执行权限
RUN chmod +x /opt/bitnami/redis/modules/*.so
```
Step3:Using https://github.com/bitnami/charts/tree/main/bitnami/redis-cluster
loadmodule
```
    ################################## MODULES #####################################

    # Load modules at startup. If the server is not able to load modules
    # it will abort. It is possible to use multiple loadmodule directives.
    #
    loadmodule /opt/bitnami/redis/modules/rejson.so
    loadmodule /opt/bitnami/redis/modules/module-oss.so
```
Install bitnami/redis-cluster in K8s
```
[root@k8s-master01 redis-cluster]# helm install -n redis-cluster redis-cluster-production .
```
<img width="1627" alt="image" src="https://user-images.githubusercontent.com/41875799/197415943-504e27d9-8ffb-4b36-bb1e-a33620f2b347.png">

**Comment by dwzkit** [comment]
> From your screenshot, it looks like you have a quite complex network setup mixing all the RFC1918 internal IP address spaces. Maybe we should check if all the IPs listed in the above screenshots, including the k8s svc ClusterIP, are accessible by your rueidis client first.

Step1:In addition to the Cluster IP of the SVC, the IP addresses of all Pod nodes are added
<img width="1798" alt="image" src="https://user-images.githubusercontent.com/41875799/197416640-afad29e0-39e6-4989-85f2-624bad7472f0.png">

Step2:Just like when only the SVC Cluster domain name was added,FT.SEARCH can sometimes return the result, sometimes "context deadline exceeded" will occur.
<img width="1916" alt="image" src="https://user-images.githubusercontent.com/41875799/197416813-3b6ef343-faf6-4c20-a16a-6599bf73651d.png">
<img width="1902" alt="image" src="https://user-images.githubusercontent.com/41875799/197416835-4aee2586-6b6e-48d2-af66-0febd19f319e.png">

**Comment by rueian** [comment]
Hi @dwzkit, I will try reproduce the problem according to your steps today.

Besides that, does the timeout also occur on GET, SET commands?

**Comment by dwzkit** [comment]
> 

Thanks!

I executed JSON.SET 800,000 times using the rueidis client with no error

If you are planning to build a redis cluster on k8s, there are 2 more things to note based on my experience.

1、Installing bitnami/redis-cluster with helm requires configuring StorageClass
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/41875799/197430267-06f4df34-b4aa-4eb8-99a8-c92352efd569.png">

2、Modify ConfigMap Added rejson and research module
<img width="1378" alt="image" src="https://user-images.githubusercontent.com/41875799/197430422-26ff4e4b-7f6a-49bc-a424-3a09172ece1b.png">

In fact, FT.SEARCH can be executed normally in the beginning using rueidis client, but for some reason "context deadline exceeded" starts to occur.

**Comment by dwzkit** [comment]
I did some new tests,I put all of the FT.SEARCH statement  which using rueidis to execut into txt file, then use redis cli command line to batch execution, all the execution succeeded.But the same FT.SEARCH command through rueidis occurs context deadline exceeded after 4-5 statements have been executed.

**Comment by rueian** [comment]
Hi @dwzkit,

I just followed your instructions on GKE, but I couldn't reproduce the issue. Here is how I made the image:
```Dockerfile
FROM bitnami/redis-cluster:7.0.5-debian-11-r0
COPY module-oss.so / # this is built according to your instructions
COPY rejson.so /     # this is copied from redislabs/rejson:edge image
```
The image is also published to dockerhub `rueian/bitnami-redis-cluster-redisearch:latest`

And this is how I used `helm` to deploy:
```sh
helm upgrade --timeout 600s --set image.repository=rueian/bitnami-redis-cluster-redisearch --set image.tag=latest --set usePassword=false myrelease my-repo/redis-cluster
```

Then I used `kubectl edit configmap myrelease-redis-cluster-default` to add `loadmodule` instructions and then restart all pods:

<img width="776" alt="image" src="https://user-images.githubusercontent.com/2727535/197563298-e51aca64-4cb6-4957-98e8-2b1059f08a1c.png">

<img width="1376" alt="image" src="https://user-images.githubusercontent.com/2727535/197563605-26626870-f3e4-413b-8118-b0aa84ac6f76.png">

Finally, ran this script:
```go
package main

import (
	"context"
	"fmt"
	"strconv"

	"github.com/rueian/rueidis" // v0.0.81
)

func main() {
	ctx := context.Background()
	c, err := rueidis.NewClient(rueidis.ClientOption{InitAddress: []string{"10.72.1.20:6379"}})
	if err != nil {
		panic(err)
	}
	defer c.Close()

	fmt.Println(c.Do(ctx, c.B().FtCreate().Index("idx").OnJson().Schema().FieldName("$.name").As("name").Numeric().Build()).Error())

	for i := 0; i < 100000; i++ {
		id := strconv.Itoa(i)
		if err := c.Do(ctx, c.B().JsonSet().Key(id).Path("$").Value(`{"name": `+id+`}`).Build()).Error(); err != nil {
			panic(err)
		}
	}

	for i := 0; i < 100000; i++ {
		id := strconv.Itoa(i)
		fmt.Println(c.Do(ctx, c.B().FtSearch().Index("idx").Query("@name:["+id+" "+id+"]").Build()))
	}
}
```
I tried many times and no timeout.

----

With the current information:
1. `What will happen if setting ClientOption.ConnWriteTimeout to -1? => There was no panic, but there was also no response`
2. `I put all of the FT.SEARCH statement which using rueidis to execut into txt file, then use redis cli command line to batch execution, all the execution succeeded`

I think it is likely some of your redis pods really stopped responding, since the difference between rueidis and redis-cli is rueidis will send the ft.search command to a random master every time.

Could you try using this script to see if it is always timed out on the same node?
```go
for addr, node := range c.Nodes() {
	fmt.Println(addr)
	for i := 0; i < 10; i++ {
		fmt.Println(node.Do(ctx, node.B().FtSearch().Index("...").Query("...").Build()))
	}
}
```

**Comment by dwzkit** [comment]
<img width="822" alt="image" src="https://user-images.githubusercontent.com/41875799/197751519-eebe5eed-1052-46c7-8493-e64a230b426f.png">
It seems that your version of Rejson does not support Chinese,I will use your image to build another rejson that supports Chinese then test again

**Comment by dwzkit** [comment]
I compiled the latest version of rediSearch (v2.4.15 module-oss.so), So far, the test results are OK. . Obviously, the problem is not caused by rueidis. If there is a new situation, I will feedback agian. Thanks a lot!^_^
