### ISSUE TITLE
A generic method for executing Redis commands

### ISSUE THREAD

**Issue by lgothard** [rueian/rueidis#11]
Similar to Redigo: `n, err := conn.Do("APPEND", "key", "value")` something like ... `c.Do(ctx, c.B().Command("APPEND", "key", "value").Build())`

This would enable users to use new/existing modules not currently supported #10 [RedisGears Support]

**Comment by rueian** [comment]
Hi @lgothard,

Thank you for filing the issue. Unfortunately, the `Command` is already used.
I think `Arbitrary` is a good alternative. It is also much clear about what it means.

**Comment by lgothard** [comment]
@rueian Excellent!!!  Thank you for such a quick response.
