### ISSUE TITLE
question: about newRing 2<<(factor-1)

### ISSUE THREAD

**Issue by dchaofei** [rueian/rueidis#110]
Hi, this project is great, so I'm looking at its source code.

https://github.com/rueian/rueidis/blob/9153856a78cb67a1bf4d3fad7711f91c934c4d14/ring.go#L21-L24
I am a little curious, why is it not `1<<factor` but `2<<(factor-1)`, where factor is always greater than 0, so it seems that the results of the two methods are the same, is there any special meaning?

**Comment by rueian** [comment]
> Hi, this project is great, so I'm looking at its source code.
> 
> https://github.com/rueian/rueidis/blob/9153856a78cb67a1bf4d3fad7711f91c934c4d14/ring.go#L21-L24
> 
> 
> I am a little curious, why is it not `1<<factor` but `2<<(factor-1)`, where factor is always greater than 0, so it seems that the results of the two methods are the same, is there any special meaning?

Hi @dchaofei, there is no special meaning for that 😆

**Comment by dchaofei** [comment]
😉
