### ISSUE TITLE
FTAGGREGATE FAiling with Group and SortBy Max

### ISSUE THREAD

**Issue by nicolastakashi** [rueian/rueidis#112]
I'm trying to run the following query to group and sort by max results.

After I execute the query I'm getting the following issue.

```golang
cursor, err := s.repository.Aggregate(context, func(search om.FtAggregateIndex) om.Completed {
		return search.Query("@serviceName:api @tagKey:{ component }").LoadAll().Groupby(1).Property("@id").Reduce("COUNT").Nargs(0).Sortby(1).Property("@id").Max(1).Build()
	})
```

```Syntax error at offset 27 near 000a3bd024df88a9```

If I run the query on RedisInsigth it works as expected.

```
FT.AGGREGATE "data" "@serviceName:api @tagKey:{ component }" GROUPBY 1 @id REDUCE COUNT 0 SORTBY 1 @id MAX 1
```

**Comment by rueian** [comment]
Hi @nicolastakashi,

I have tried your query with redisearch:2.4.9, but did not get the same `Syntax error`.

It seems to me that your `Syntax error` did not come from the `s.repository.Aggregate`, since there was a wired `000a3bd024df88a9`.

**Comment by nicolastakashi** [comment]
Hey @rueian!
THanks for the fast reply, when I was debugging to get more details I figured out that it was an issue on my side, sorry for bothering you.

You can close this.
