### ISSUE TITLE
Repository Search only returning 10 itens even index has 10k

### ISSUE THREAD

**Issue by nicolastakashi** [rueian/rueidis#116]
I'm running the following code:

```golang
_, spans, err := s.repository.Search(context, func(search om.FtSearchIndex) om.Completed {
    return search.Query("@traceID:(0000000000000011)").Build()
})
```

I've around 10k items on my index, but this expression is only returning to me 10 items, but if I run the following expression on Redis Insight I got the 10k itens.

```
FT.SEARCH "jsonidx:spans" "@traceID:(0000000000000011)"
```

Is there any default limitation?

**Comment by rueian** [comment]
Hi @nicolastakashi,

Yes, the default limit is 10 records according to https://redis.io/commands/ft.search/:
<img width="663" alt="image" src="https://user-images.githubusercontent.com/2727535/199238471-e12126e8-621b-482a-8b25-df27ca5209d8.png">

If you want to change that default behavior, please also note that the cost of `FT.SEARCH` is proportional to the number of document returned. Return too many records will block you redis server too long.
<img width="695" alt="image" src="https://user-images.githubusercontent.com/2727535/199238344-37efd274-157e-4c6e-b1d6-3054bde69468.png">
