### ISSUE TITLE
Mocked match failures in a DoMulti call panic instead of returning an error

### ISSUE THREAD

**Issue by dqsully** [rueian/rueidis#120]
Whenever the `mock.Match(...args)` doesn't match for a `DoMulti()` call, it causes a panic with the message `panic: interface conversion: interface {} is []cmds.Completed, not cmds.Completed` from here: https://github.com/rueian/rueidis/blob/09c7d503ab6dd5a7da9fdb3bbc58458985d4596b/mock/match.go#L52

This appears to be due to a weird gomock fallback match algorithm for functions with variadic arguments here: https://github.com/golang/mock/blob/v1.6.0/gomock/call.go#L373

Here's a simple test that creates the panic:
```go
package example

import (
	"context"
	"testing"

	"github.com/golang/mock/gomock"
	"github.com/rueian/rueidis"
	"github.com/rueian/rueidis/mock"
)

func TestRueidisSimple(t *testing.T) {
	ctrl := gomock.NewController(t)
	defer ctrl.Finish()

	ctx := context.Background()
	redis := mock.NewClient(ctrl)

	redis.EXPECT().DoMulti(
		ctx,
		mock.Match("PING"),
	).Return(
		[]rueidis.RedisResult{
			mock.Result(mock.RedisString("PONG")),
		},
	)

	redis.DoMulti(ctx, redis.B().Ping().Message("hi").Build())
}
```

**Comment by rueian** [comment]
Hi @dqsully,

Thank you for reporting this issue. The fix will be in the next release.
