### ISSUE TITLE
Synonyms for exporting internal objects

### ISSUE THREAD

**Issue by mdigger** [rueian/rueidis#121]
If you add synonyms to the library for exporting internal objects, then everything should be normalized:

```golang
package rueidis

import "github.com/rueian/rueidis/internal/cmds"

// Exported synonyms for command types.
type (
    Completed = cmds.Completed
    Cacheable = cmds.Cacheable
    Builder   = cmds.Builder
)
```

1. The error with VSCode with the "substitution" of `cmds.Completed` will be removed.
2. It will be possible to create functions that return prepared Redis commands:
    ```golang
    type Object struct {
        ID        string
        Datetime time.Time
        Message string
    }

    func (o Object) SaveCmd(client rueidis.Client, id string) rueidis.Completed {
        return client.B().
            Hset().
            Key("out:interval:"+o.ID).
            FieldValue().
            FieldValue("datetime", fmt.Sprint(o.Datetime.Unix())).
            FieldValue("message", o.Message).
            Build()
    }
    ```
3. Can be used in the interface description
    ```golang
    type Client interface {
        B() Builder
        Do(ctx context.Context, cmd Completed) (resp RedisResult)
        DoMulti(ctx context.Context, multi ...Completed) (resp []RedisResult)
        DoCache(ctx context.Context, cmd Cacheable, ttl time.Duration) (resp RedisResult)
        DoMultiCache(ctx context.Context, multi ...CacheableTTL) (resp []RedisResult)
        Receive(ctx context.Context, subscribe Completed, fn func(msg PubSubMessage)) error
        Dedicated(fn func(DedicatedClient) error) (err error)
        Dedicate() (client DedicatedClient, cancel func())
        Nodes() map[string]Client
        Close()
    }
    ```

**Comment by rueian** [comment]
Hi @mdigger,

Thank you for your suggestion and the PR #122.

Moving the `cmds.Completed` out of `github.com/rueian/rueidis/internal` is what I am considering since my first commit to this library.

But even today, I still don't figure out other ways to make the following code fail to be compiled unless I make the `cmds.Completed` live in `internal` packge:

```go
client.Do(ctx, cmds.Completed{})
// or
client.Do(ctx, cmds.Completed(c.B().Set().Key("I am not a completed cmd")))
```

I think letting the above code won't pass the compiler is quite important. This could prevent users to make some mistakes.

**Comment by mdigger** [comment]
Thank you for the detailed answer!

It is possible that I am wrong, but it seems to me that using inaccessible types in the library gives more problems than solutions.

**Comment by rueian** [comment]
You are right. The inaccessible type indeed creates some problems.

In addition to the disability you just mentioned to have prepared command function, the inaccessible type in the `Client` interface also prevent users from hooking or mocking it. That is why there are [github.com/rueian/rueidis/mock](https://github.com/rueian/rueidis/tree/master/mock) and [github.com/rueian/rueidis/rueidishook](https://github.com/rueian/rueidis/tree/master/rueidishook) provided in this library.
