### ISSUE TITLE
i have custom redis server that accepts command <- the only thing without key or value. how do i send just the command?

### ISSUE THREAD

**Issue by ultperf** [rueian/rueidis#124]
how do i send just the command?
c.B().Arbitrary("[RANDOMVALUES]").Keys().Args().Build() <-- will this work? my RANDOMVALUES is anything as command

```
Arbitrary command
If you want to construct commands that are not yet supported, you can use c.B().Arbitrary():

// This will result into [ANY CMD k1 k2 a1 a2]
c.B().Arbitrary("ANY", "CMD").Keys("k1", "k2").Args("a1", "a2").Build()
```

**Comment by rueian** [comment]
Hi @ultperf,

Just `c.B().Arbitrary("RANDOMVALUES").Build()` should work.

**Comment by ultperf** [comment]
thx!

**Comment by ultperf** [comment]
resp := c.B().Arbitrary("RANDOMVALUES").Build().ToString() <- no to string... how to work around?

**Comment by rueian** [comment]
Hi @ultperf,

To send the command to redis, you will need to pass it into `c.Do`, for example:

```go
cmd := c.B().Arbitrary(…).Build()
resp, err := c.D(ctx, cmd).ToString()
```

**Comment by ultperf** [comment]
thx again!
