### ISSUE TITLE
one last question / problem regarding Arbitrary() sending of []byte instead of string

### ISSUE THREAD

**Issue by ultperf** [rueian/rueidis#128]
as my client command is customized, so is my customized redis server.
1. the issue is, i tried converting []byte to string to send but it's not received properly.
2. how do i send []byte as a command? the command is []byte and that's all actually. 

how do i resolve this?
maybe one last question. how do i receive response as []byte too instead of string?

```
     var fwBytesOne []byte = []byte("hello")
     fwResStr, err := credis.Do(ctx, credis.B().Arbitrary(string(fwBytesOne)).Build()).ToString()
```

thx for helping to get this far. this shld be all i need. thx!

**Comment by rueian** [comment]
Hi @ultperf,

> the issue is, i tried converting []byte to string to send but it's not received properly.

That should work. What do you receive instead?

> how do i receive response as []byte too instead of string?

You can use `.AsReader()` instead of `.ToString()`

**Comment by ultperf** [comment]
i receive "HELLO" <- this is not the req sent.
i tested with the other script and got 
HELLO 
CLIENT

i think this does some... connection kind of thing? not sure. what kind of response do i need to send from my custom server first for this 
HELLO
and 
CLIENT
thing?

**Comment by rueian** [comment]
Duplicate with https://github.com/rueian/rueidis/issues/129
