### ISSUE TITLE
can i have your expert opinion regarding \r\n vs custom \n just to save 1 byte

### ISSUE THREAD

**Issue by ultperf** [rueian/rueidis#130]
can i have your expert opinion regarding \r\n vs custom \n just to save 1 byte for high speed redis transmission
how can i make it even faster? (with redis)

is it advisable for me to change \r\n to just \n on both client and server side?
what's ur opinion on this? thx in advance.

**Comment by rueian** [comment]
Hi @ultperf,

I guess you are talking about the `inline commands` protocol, right? https://redis.io/docs/reference/protocol-spec/#inline-commands

The `inline commands` protocol is only useful when you are talking to redis with your hand and keyboard.

The binary-safe way to send commands is using RESP array https://redis.io/docs/reference/protocol-spec/#resp-arrays. There is no `\r\n` or `\n` at all.

**Comment by ultperf** [comment]
yes u are right but isnt CRLF 2 bytes? we can shave it to 1 byte with LF '\n' right? just LF.
if i replace all CRLF with LF, will that save 1 byte in wire transmission?

**Comment by rueian** [comment]
Yes, it will. But if you use binary-safe protocol, there will be no LF at all.

**Comment by ultperf** [comment]
ok thx! pls help with the last area i've asked. i cant seem to get the pipe / rueidis modification to work

```
 interface conversion: rueidis.Client is nil, not *rueidis.clusterClient: 
 ```
