### ISSUE TITLE
[Question] Does rueidis use singleflight internally?

### ISSUE THREAD

**Issue by SaikiranDaripelli** [rueian/rueidis#135]
Does rueidis use single flight internally for any cache operations or do i need to wrap  commands with singleflight if i need to avoid  cache flooding in case of cache miss/local cache miss etc.?

**Comment by rueian** [comment]
Hi @SaikiranDaripelli,

Yes, rueidis does single flight internally if DoCache() misses local cache.

**Comment by SaikiranDaripelli** [comment]
Does even Do() calls wrapped in singleflight or only when we use client side caching?

**Comment by rueian** [comment]
No, Do() doesn’t wrapped in sigleflight. It will send the command you passed to redis directly.

**Comment by SaikiranDaripelli** [comment]
Thank you.
