### ISSUE TITLE
everything shld be working fine now. thx. sort of "related issues"

### ISSUE THREAD

**Issue by ultperf** [rueian/rueidis#137]
coz doing some extreme connection speed, was wondering how do you:
1. do rpc compression over tcp transfer? i'm using custom redis server but i'm sure there's a way i can easily mod my server and your client to do tcp compression transfer right? if so, which part of the pipelined client request should i look at? which file?

2. do you know how to do IPC through shm using the redis client over my custom redis server?

**Comment by rueian** [comment]
Hi @ultperf,

> do rpc compression over tcp transfer? i'm using custom redis server but i'm sure there's a way i can easily mod my server and your client to do tcp compression transfer right? if so, which part of the pipelined client request should i look at? which file?

You can do the compression inside the reader and writer interface here:
https://github.com/rueian/rueidis/blob/121d5bf34785327ce869c56b7e83304420bbadd6/pipe.go#L82-L83

> do you know how to do IPC through shm using the redis client over my custom redis server?
No, I don't know. I believe if you do IPC through share memory, then you don't need custom redis server and client at all.
