### ISSUE TITLE
How do you SUBSCRIBE to a channel?

### ISSUE THREAD

**Issue by amnonbc** [rueian/rueidis#139]
Do you have any example code?

**Comment by rueian** [comment]
Hi @amnonbc,

There are two ways:

1. https://github.com/rueian/rueidis#pubsub
2. https://github.com/rueian/rueidis#alternative-pubsub-hooks

**Comment by amnonbc** [comment]
Thanks @rueian 

It tried 

```
package main

import (
	"context"
	"fmt"
	"github.com/rueian/rueidis"
	"log"
	"time"
)

func main() {
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()
	c, err := rueidis.NewClient(rueidis.ClientOption{
		InitAddress: []string{"127.0.0.1:6379"},
	})
	if err != nil {
		panic(err)
	}
	defer c.Close()

	c.Do(ctx, c.B().Publish().Channel("ch").Message("msg1").Build())

	done := make(chan struct{})
	go func() {
		comm := c.B().Subscribe().Channel("ch").Build()
		err := c.Receive(ctx, comm, func(msg rueidis.PubSubMessage) {
			fmt.Println(msg.Message)
			close(done)
		})
		log.Println(err)
	}()
	c.Do(ctx, c.B().Publish().Channel("ch").Message("hi").Build())
	select {
	case <-done:
		log.Println("got sub message")
	case <-ctx.Done():
		log.Println(ctx.Err())
	}
}
```

https://go.dev/play/p/_wJP2GhBLBu

But I get  context deadline exceeded on lines 31 and 38.
What am I doing wrong?

**Comment by amnonbc** [comment]
Great! That works.

Just trying to figure out how I can get the maximum throughout and minimize the number of context switches.

**Comment by amnonbc** [comment]
Tried benchmarking against go-redis and found similar performance.

My code is on https://github.com/amnonbc/redistest

```
~/redistest$ /bin/time rueian/rueian -n 100000
3.52user 7.18system 0:10.39elapsed 103%CPU (0avgtext+0avgdata 9516maxresident)k
0inputs+0outputs (0major+1901minor)pagefaults 0swaps

~/redistest$ /bin/time ./standardlib/standardlib -n 100000
redistest.go:53: got 100000 messages in 10.621125625s
3.80user 6.89system 0:10.62elapsed 100%CPU (0avgtext+0avgdata 10676maxresident)k
0inputs+0outputs (0major+1981minor)pagefaults 0swaps
```

**Comment by rueian** [comment]
Hi @amnonbc, thank you for sharing your benchmark.

However, it seems to me that the `delay` in your benchmark is quite confusing if you want to push the client to the limit.

To achieve better performance, you could change [this](https://github.com/amnonbc/redistest/blob/66b7f01b01d06480793144c76d8540f8e5dbf807/rueian/redistest.go#L47):
```go
func publisher(ctx context.Context, c rueidis.Client) {
	tick := time.NewTicker(delay)
	defer tick.Stop()

	for range tick.C {
		err := c.Do(ctx, c.B().Publish().Channel("ch").Message("msg").Build()).Error()
		...
	}
}
```

to either this:
```go
func publisher(ctx context.Context, c rueidis.Client) {
	for i := 0; i < numMsgs; i++ {
		go func() {
			err := c.Do(ctx, c.B().Publish().Channel("ch").Message("msg").Build()).Error()
			...
		}()
	}
}
```

or this:
```go
func publisher(ctx context.Context, c rueidis.Client) {
	msgs := make(rueidis.Commands, numMsgs)
	for i := range msgs {
		msgs[i] = c.B().Publish().Channel("ch").Message("msg").Build()
	}
	for _, resp := range c.DoMulti(ctx, msgs...) {
		err := resp.Error()
		...
	}
}
```

**Comment by amnonbc** [comment]
Thanks @rueian ,
I updated the benchmark as suggested

```
% time ./standardlib/standardlib -n 100000
redistest.go:51: got 100000 messages in 5.213545974s

real	0m5.218s
user	0m1.970s
sys	0m3.465s
%
% time ./rueian/rueian -n 100000 -b 1
2022/11/18 14:35:58 got 100000 messages in 5.797057133s

real	0m5.803s
user	0m1.584s
sys	0m4.100s
%
%
%  time ./rueian/rueian -n 100000 -b 1000
2022/11/18 14:36:08 got 100000 messages in 300.503933ms

real	0m0.306s
user	0m0.197s
sys	0m0.039s
%
```

So when running the publish commands back-to-back, we get similar performance from rueidis as go-redis.
But if we introduce batching, as you suggested, then we get a x10 speedup.

The problem is that the way my service is structured, there is not a natural way of batching the publish operations.

**Comment by rueian** [comment]
> The problem is that the way my service is structured, there is not a natural way of batching the publish operations.

Sure, it is a common scenario that there is no way to do batching from the upper level. Therefore, rueidis automatically batches **concurrent** requests for you , for example:

```go
func publisher(ctx context.Context, c rueidis.Client) {
	for i := 0; i < numMsgs; i++ {
		go func() {
			err := c.Do(ctx, c.B().Publish().Channel("ch").Message("msg").Build()).Error()
			...
		}()
	}
}
```

The result should be faster than 5s. This might be much useful to you If your service is a HTTP/gRPC or other RPC server.
