### ISSUE TITLE
question regarding .AsReader

### ISSUE THREAD

**Issue by ultperf** [rueian/rueidis#141]
can u pls help simplify this for speed?
fwRes is []byte. possible to pass as byte instead of string conversion?
```
  var fwRes []byte = []byte("something")
  
  ioReaderData, err := credis.Do(ctx, credis.B().Arbitrary(string(fwRes)).Build()).AsReader()
  buf := &bytes.Buffer{}
  buf.ReadFrom(ioReaderData)
```

do i have to manually convert io.Reader to []byte?

**Comment by rueian** [comment]
Use `rueidis.BinaryString` to convert a byte slice to a string without copy.

Use io.ReadAll to read all bytes to []byte

**Comment by ultperf** [comment]
ioReaderData, err := credis.Do(ctx, credis.B().Arbitrary(rueidis.BinaryString(fwRes)).Build()).AsReader()
  data := io.ReadAll(ioReaderData) // <- like this?

**Comment by rueian** [comment]
Yes. Just be aware that the return of `io.ReadAll` is ([]byte, error)

**Comment by ultperf** [comment]
got it. thx
