### ISSUE TITLE
everything's great! how to do unix domain socket?

### ISSUE THREAD

**Issue by ultperf** [rueian/rueidis#142]
everything's great! how to do unix domain socket?

i think this is my final question :) do mention how i can repay your kindness for all the help extended!

**Comment by rueian** [comment]
You can change this function to connect to Unix domain socket

https://github.com/rueian/rueidis/blob/2d84b3ce34c335f39933ce02d7a89aef280e8cd8/rueidis.go#L285

**Comment by ivanduka** [comment]
Hi, do I understand it correct that there is no way to connect to Unix socket without forking this repo?

**Comment by rueian** [comment]
> Hi, do I understand it correct that there is no way to connect to Unix socket without forking this repo?

Not really. You can pass your own dialer implementation to rueidis.NewClient.
