### ISSUE TITLE
initially ok but after a while using, my customized rueidis connection is "stuck"

### ISSUE THREAD

**Issue by hiqsociety** [rueian/rueidis#143]
initially ok but after a while using, my customized rueidis connection is "stuck" sending with 100% cpu. any ideas why? it's sending part.
i think either
1. connection dropped or 
2. sending failed for whatever reason.
using the Get pool version mentioned previously.

i've disabled PING. not sure what else to disable etc.

**Comment by ultperf** [comment]
how do i disable pipeline mode?

**Comment by rueian** [comment]
You could use `kill -3 pid` to terminate your program with a goroutine dump. From the dump, you could see where it stuck on.

Pipeline mode will not be enabled until you send concurrent requests through the client. Once enabled, it will always use pipeline mode and there is no way to disable it.

Actually, pipelining is native behavior of bidirectional connection, such as tcp. I think any server should support pipelining natively without configuration if it use such connection for communication with clients.

**Comment by ultperf** [comment]
everything's running fine now. i think something to do with "QUIT" command issued (automatically) not sure.

1. how do i disable being issued quit command?
2. does this client issue "additional" commands that is not normally issued manually? seems like a lot of background things going without developer input. so just want to make sure no more hiccups just in case. i "disabled" being issued "QUIT" command and it's running fine now. what else shld i be looking out for?

**Comment by ultperf** [comment]
after some time, it freezes according to the pool u sent.
i think the connection is closed or something but i cant confirm.

do u have a ruiedis pool at hand? please make this possible. thx

**Comment by rueian** [comment]
I am sorry, but I don't get what pool you are referring to.
