### ISSUE TITLE
ERR wrong number of arguments for 'expire' command

### ISSUE THREAD

**Issue by 23233** [rueian/rueidis#145]
Version: 0.0.84

```
// add
Inst.trdb.B().Set().Key("testExpire").Value("1").ExSeconds(60).Build()
// set Expire
Inst.trdb.B().Expire().Key("testExpire").Seconds(86400).Gt().Build()
```

I'm try use `Nx` `Xx` `Gt` `Lt` .

All options command , Same error :

**ERR wrong number of arguments for 'expire' command**
![image](https://user-images.githubusercontent.com/12870070/202887556-3bde5dbe-3780-4123-b088-6aa6511e1a89.png)

## Add 
![image](https://user-images.githubusercontent.com/12870070/202887671-eeb5cba3-67eb-49e6-9c92-27875520e1ac.png)

## Set
![image](https://user-images.githubusercontent.com/12870070/202887680-e836dc2f-8632-4005-b3d9-c068541a3e6e.png)

**Comment by rueian** [comment]
Hi @23233,

Are you using Redis 7? The NX, XX, GT and LT are only supported in Redis >= 7

**Comment by 23233** [comment]
Hi ~  @rueian
I'm see that
![image](https://user-images.githubusercontent.com/12870070/202888257-7d8efd3a-059d-4cc1-88b0-517ca6060571.png)

I'm Redis version is `6.2.6`  , I'm try to update redis version , fix this!

Thanks~
