### ISSUE TITLE
Mock client fails for multi-key delete

### ISSUE THREAD

**Issue by SaikiranDaripelli** [rueian/rueidis#146]
Mock client passes InitSlot for new cmd builder while actual client in case of single-node cluster passes NOSLOT and because of it  multi-key delete tests are failing for me with
`multi key command with different key slots are not allowed`

is it possible to enhanace it to support both cases?

**Comment by rueian** [comment]
Sure, I will add `mock.WithSlotCheck()` option in the next version.

You will be able to use it like this `mock.NewClient(ctrl, mock.WithSlotCheck())`

**Comment by SaikiranDaripelli** [comment]
Tried it against main with latest commit, and it is working for my usecase. Thanks you @rueian

**Comment by SaikiranDaripelli** [comment]
@rueian  Is there any way to extend mock to add more matchers? problem i am facing now is to mock/expect a SET command and i want to match Any string for value as it doesnt seem correct to hardcode expected string value.

**Comment by rueian** [comment]
What about adding a new `MatchFn(fn func(cmd []string) bool)` method to allow you passing custom `fn` to decide matched or not?

**Comment by SaikiranDaripelli** [comment]
Yes that should solve my usecase
