### ISSUE TITLE
when is ctxRedis := context.Background() needed?

### ISSUE THREAD

**Issue by ultperf** [rueian/rueidis#163]
can i make this into a global variable?
e.g.
```
var (
  ctxRedis = context.Background()
)
```
because i dont think i'll ever need to use it?
currently used like this now. i'm not using the ctxRedis anywhere other than 

```
  ctxRedis := context.Background()
  ioReaderData, err := credis.Do(ctxRedis, credis.B().Arbitrary(rueidis.BinaryString(fwRes)).Build()).AsReader()
```

**Comment by rueian** [comment]
Yes, you can make it a global variable. Actually, the go compiler `context.Background()` will also inline it into a global variable.

**Comment by ultperf** [comment]
ok thx

**Comment by ultperf** [comment]
@rueian possible to allow ctxRedis to be a nil value? e.g.
ioReaderData, err := credis.Do(**nil**, credis.B().Arbitrary(rueidis.BinaryString(fwRes)).Build()).AsReader()

to speed up things a bit

**Comment by rueian** [comment]
Hi @ultperf, allowing nil ctx will only SLOW it down since it need to do additional check if ctx is nil or not.

**Comment by ultperf** [comment]
@rueian do u think there can be a function without needing this context part? for pushing speed a bit faster

**Comment by rueian** [comment]
The `ctx` is mostly needed. It plays a crucial role in many user interests, such as timeout, manual cancellation, and, most importantly, performance tracing.

Without the `ctx`, users will not be able to integrate the library with their performance tracing system and thus will not be able to monitor and optimize how their application interacts with Redis.

I don't think it is worth providing such a function without the `ctx`. It is just unrealistic.

**Comment by ultperf** [comment]
@rueian hmm... do hope for a version where this performance tracing can be turned off though. i just hope to push for extreme speed.

**Comment by rueian** [comment]
> can i do it this way? will it affect anything? putting context.Background() inside and no need do any ctx declaration

Sure, you can. No need to declare ctx explicitly. It won't affect anything.
