### ISSUE TITLE
How to dynamically control parameters when using RedisSearch

### ISSUE THREAD

**Issue by Angry-Chick** [rueian/rueidis#166]
I need to dynamically control parameters such as Verbatim, Highlight, Slop... when using RedisSearch, but it is difficult for me to define a type to receive a value, because the type of the value returned by each method is different, and the most important thing is that the type is not exported.

This is how I expected it to be written:
```
var c cmds.Completed
c := cmds.Completed(r.B().FtSearch().Index(index).Query(text))
if opt.Verbatim{
	val,_ := c.(cmds.FtSearchQuery)
	c = cmds.Completed(val.Verbatim())
}
if opt.Highlight{
	val,_ := c.(cmds.FtSearchVerbatim)
	c = cmds.Completed(val.Highlight())
}
...
```

**Comment by FZambia** [comment]
Hello @Angry-Chick 

Probably you are looking for this: https://github.com/rueian/rueidis/blob/e806b49ff57094e14eb87ecb0c94b5bd4f4d1464/cmds.go#L19

**Comment by rueian** [comment]
Hi @Angry-Chick,

I plan to export `cmds.Completed` in the future release (https://github.com/rueian/rueidis/pull/122). However `cmds.FtSearchQuery` and `cmds.FtSearchVerbatim` will still be private.

For constructing the command conditionally, you can use the https://github.com/rueian/rueidis#arbitrary-command:
```go
cmd := c.B().Arbitrary("FTSEARCH").Keys("xxx_index")
if opt.Verbatim {
	cmd = cmd.Args("...", "...")
}
if opt.Highlight {
	cmd = cmd.Args("...", "...")
}
client.Do(ctx, cmd.Build())
```

**Comment by rueian** [comment]
Hi @Angry-Chick,

Are you still bothered by this issue?

**Comment by rueian** [comment]
Hi @Angry-Chick, please reopen this or create a new issue if you still need some help.
