### ISSUE TITLE
works fantastic but i'm not that smart to understand the underlying mechanism of auto pipelining...

### ISSUE THREAD

**Issue by ultperf** [rueian/rueidis#167]
> All non-blocking concurrent commands are automatically pipelined through connections, which reduces the overall round trips and system calls, and gets higher throughput.

questions:
1. can u show an example of non-blocking concurrent commands vs blocking "concurrent" or "non-concurrent" commands? do u mean multi-exec in this case or... set command that does not need returned values?
    can u put this into readme of ruiedis front page under FAQ? 
    i'm using it heavily across deployments and hope that this "mechanism" is explained for reference (in terms of roadmap of ruiedis dev. i'm not sure if u are looking for us to be able to send at lowest latency or highest throughput or how to do settings for those)
2. how to set the "auto pipelining settings?" as in time (by duration) or batched connection "pushing" / command sending. (number of bytes over txn per second)
3. where is the "code section" / files that does this magic of auto pipelining? (for reference)

currently being used in production as IPC and it's working as expected. hope to push the limitations further!

when there's a buymeacoffee section, hope to be the first to buy u coffee!

**Comment by rueian** [comment]
Hi @ultperf,

The `non-blocking` I mentioned in that section refers to **Redis non-blocking** commands, such as `GET`, and `SET` commands. Whereas `BLPOP` and `XREAD BLOCK` are **Redis blocking** commands. Then the `concurrent commands` means multiple `client.Do()` invocations from multiple goroutines at the same time.

Hope that now you can understand more about this mechanism. I have updated the auto-pipelining section of the readme with more detail and a new example.

The auto-pipelining mechanism tries to fully utilize your go runtime scheduling capability by default. Currently, there are only two options to tune its behavior, which are `PipelineMultiplex` and `MaxFlushDelay` of `rueidis.ClientOption`.

All the magic behind the mechanism is at here https://github.com/rueian/rueidis/blob/main/pipe.go#L222.
