### ISSUE TITLE
How to use Scan?

### ISSUE THREAD

**Issue by sangnnc** [rueian/rueidis#168]
I am struggling to figure out how to use rueidis to perform the Scan command (https://redis.io/commands/scan/) and iterate over the response. Something that can be done using redis-go as follows:

  ```go
    var cursor uint64
	var n int
	for {
		var keys []string
		var err error
		keys, cursor, err = rdb.Scan(ctx, cursor, "key*", 10).Result()
		if err != nil {
			panic(err)
		}
		n += len(keys)
		if cursor == 0 {
			break
		}
	}

	fmt.Printf("found %d keys\n", n)
```

**Comment by rueian** [comment]
Hi @sangnnc,

Here you go:

```go
package main

import (
	"context"
	"fmt"
	"github.com/rueian/rueidis"
)

func main() {
	client, err := rueidis.NewClient(rueidis.ClientOption{InitAddress: []string{"127.0.0.1:6379"}})
	if err != nil {
		panic(err)
	}
	for _, node := range client.Nodes() { // loop all your redis nodes
		var scan rueidis.ScanEntry
		for more := true; more; more = scan.Cursor != 0 {
			if scan, err = node.Do(context.Background(), node.B().Scan().Cursor(scan.Cursor).Build()).AsScanEntry(); err != nil {
				panic(err)
			}
			fmt.Println(scan.Elements)
		}
	}
}

```

**Comment by sangnnc** [comment]
Thank you so much for the quick response. It works like a charm.

P/S: It turns out that the AsScanEntry is released in v0.0.91, which is two weeks ago.  I used the v0.0.90, therefore, I cannot find any ways to iterate a scan :D

**Comment by rueian** [comment]
Hi @sangnnc,

To inform you that v0.0.92 is out and contains a fix related to this issue: the `ScanEntry.Cursor` has been corrected to `uint64`. Please upgrade to the latest version.

If you just used the above code snippet I provided then no code change is required.

**Comment by FywOoie** [comment]
Before v0.0.90, I used the following code. It is dumb but worked
```
scan, err := client.Do(ctx, client.B().Scan().Cursor(0).Match("key*").Build()).ToAny()
if err != nil {
    // handle
}
allKeys, ok := scan.([]interface{})[1].([]string)
if !ok {
    // handle
}
```
