### ISSUE TITLE
locker not support Redis v6.0.16

### ISSUE THREAD

**Issue by xieyj-apple** [rueian/rueidis#174]
my redis server version is 6.0.16
and the locker use the PXAT is new in redis 6.2 
so i cant use it...

**Comment by rueian** [comment]
Hi @xieyj-apple,

What do think if there was a `FallbackPX` option allowing you to use `PX` instead?

**Comment by rueian** [comment]
Hi @xieyj-apple,

`FallbackSETPX` option has been added in v0.0.94
