### ISSUE TITLE
Is it possible to use Redis pipeline to efficiently write 10 million Redis JSON-formatted data in a high-throughput manner even in a Redis cluster environment?

### ISSUE THREAD

**Issue by dwzkit** [rueian/rueidis#181]
Hi,Is it possible to use Redis pipeline to efficiently write 10 million Redis JSON-formatted data in a high-throughput manner even in a Redis cluster environment? How should the specific code be written?

**Comment by rueian** [comment]
Yes, your code is correct and it looks good to me.

The little difference between the benchmark code I provided and yours is that the former one will reuse goroutines instead of keep creating and destroying goroutines.

**Comment by dwzkit** [comment]
> Yes, your code is correct and it looks good to me.
> 
> The little difference between the benchmark code I provided and yours is that the former one will reuse goroutines instead of keep creating and destroying goroutines.

I adjusted the code to be: expireInSecond := 180
```
for i, phone := range data {
  eg.Go(func() error {
    client.Do(ctx, client.B().JsonSet().Key(strconv.Itoa(i)).Path("$").Value(phone).Build()).Error()
  })
  eg.Wait()
}
```
The speed of writing to Redis has indeed become much faster. I was able to write about 150,000 pieces of data in only about 127 seconds, while previously it took more than ten minutes to write them one by one.

So I wrote the above Redis writing method as an API for other programs to call. However, when multiple programs call this API concurrently, it seems that separate and independent pipelines are established for different calls, resulting in multiple pipelines working simultaneously. This leads to a significant increase in CPU usage, up to over 95% (on an 8-core CPU with 32GB of memory).

What is the best way for me to optimize this situation?

**Comment by rueian** [comment]
Did you put eg.Wait() inside the loop? I believe it should be outside the loop at least to utilize the auto pipelining technique.

Besides that, you should use DoMulti() to send JSON.SET and EXPIRE commands at once.

> it seems that separate and independent pipelines are established for different calls, resulting in multiple pipelines working simultaneously.

No, there won’t be independent pipelines established for different calls. They shared same pipelines to each Redis nodes.

> This leads to a significant increase in CPU usage, up to over 95%

As mentioned previously, keep recreating goroutines is the most easiest way doing something like this. However, this way will cause some CPU overhead. You can try to reuse goroutines to remove those overhead.

Another thing is that handling remote calls from external programs is very expensive. You should take some pprof snapshots for further improvement.

**Comment by dwzkit** [comment]
> The new code make me confused. Did you put eg.Wait() inside the loop? I believe it should be outside the loop at least to utilize the auto pipelining technique.
> 
> Besides that, you should use DoMulti() to send JSON.SET and EXPIRE commands at once.
> 
> > it seems that separate and independent pipelines are established for different calls, resulting in multiple pipelines working simultaneously.
> 
> No, there won’t be independent pipelines established for different calls. They shared same pipelines to each Redis nodes.
> 
> > This leads to a significant increase in CPU usage, up to over 95%
> 
> As mentioned previously, keep recreating goroutines is the most easiest way doing things like this. However, this way will cause some CPU overhead. You can try to reuse goroutines to remove those overhead.
> 
> Another thing is that handling remote calls from external programs is very expensive. You should take some pprof snapshots for further improvement.



> eg.Wait()

Sorry, it was a typo. Actually, the eg.Wait() should be placed outside of the loop.In my actual program, eg.Wait() is placed outside of the loop.

Based on the optimization ideas you provided, I will try to optimize it again.

**Comment by dwzkit** [comment]
> The new code make me confused. Did you put eg.Wait() inside the loop? I believe it should be outside the loop at least to utilize the auto pipelining technique.
> 
> Besides that, you should use DoMulti() to send JSON.SET and EXPIRE commands at once.


```
for _, resp := range client.DoMulti(ctx, client.JsonSet().Key(key).Path("$").Value(string(jsons)).Build(), client.Expire().Key(key).Seconds(expireInSecond).Build()) {
if err = resp.Error(); err != nil {
	panic(err)
  }
}
```

I changed the way the code above is written, and the program can run properly. However, I am not sure if what I wrote is correct.Is this written correctly?

**Comment by dwzkit** [comment]
> Another thing is that handling remote calls from external programs is very expensive. You should take some pprof snapshots for further improvement.

I don't have a very good understanding of the working mechanism of Redis pipeline. When you mentioned "handling remote calls from external programs is very expensive," my own understanding is that in a high-concurrency API request scenario, even if goroutines are reused (creating a goroutine pool, waiting in the queue when there are no available goroutines), it will still cause a high workload for Redis pipeline？

If my understanding is correct, would it be better to add message queuing such as RocketMQ before writing to Redis, cache all API request data to the message queue first, and then gradually write the data to be written from the message queue according to the performance level that the Redis server can withstand?

**Comment by rueian** [comment]
> > The new code make me confused. Did you put eg.Wait() inside the loop? I believe it should be outside the loop at least to utilize the auto pipelining technique.
> > Besides that, you should use DoMulti() to send JSON.SET and EXPIRE commands at once.
> 
> ```
> for _, resp := range client.DoMulti(ctx, client.JsonSet().Key(key).Path("$").Value(string(jsons)).Build(), client.Expire().Key(key).Seconds(expireInSecond).Build()) {
> if err = resp.Error(); err != nil {
> 	panic(err)
>   }
> }
> ```
> 
> I changed the way the code above is written, and the program can run properly. However, I am not sure if what I wrote is correct.Is this written correctly?

Yes, it is correct.

> When you mentioned "handling remote calls from external programs is very expensive,"

I mean receiving and decoding those remote requests are very expensive. They may have already  taken a lot of your CPU usage.


> If my understanding is correct, would it be better to add message queuing such as RocketMQ before writing to Redis

Your understanding is correct. However, your message queuing needs to be faster than redis, or it won’t be better.

**Comment by dwzkit** [comment]
Thank you for your answer. I will try to optimize and upgrade in the next two weeks. I will close the issue for now, and if I have any new questions, I will reopen it. Thank you.
