### ISSUE TITLE
adding field projection to om repositories

### ISSUE THREAD

**Issue by jamshidi799** [rueian/rueidis#186]
hi guys. I have two question

1.  will you accept this feature? it seems easy to modify the parsing algorithm in the Search function and I can handle it
2.  are we have a contribution doc?

thanks

**Comment by rueian** [comment]
Hi @jamshidi799,

We don't have a contribution doc currently. PRs are just welcome.

However, how would the field projection work with Object Mapping? They seem to have conflicts.

**Comment by jamshidi799** [comment]
if we build a query like this:

`
search.Query(query).
Return("12").
Identifier("$.id").Identifier("as").Identifier("id").
Identifier("$.title").Identifier("as").Identifier("title").
Build()
`

**Comment by jamshidi799** [comment]
if we build a query like this:

`
search.Query(query).Return("6").Identifier("$.id").Identifier("as").Identifier("id").Identifier("$.title").Identifier("as").Identifier("title").Build()
`

then Redisearch returns this response:

1) "24"
2) "product:59668"
3) .1) "id"
     2) "59668"
     3) "title"
     4) "hello world"

then I think we can use reflection and JSON tag and map response to the object

**Comment by jamshidi799** [comment]
I realized the conflict. thanks for your reply
