### ISSUE TITLE
Auto Pipelining Strategy

### ISSUE THREAD

**Issue by dwzkit** [rueian/rueidis#189]
I have a server-side API interface called StoreNum, which is designed to receive an array of numbers, store them in Redis using Auto Pipelining technology.
```
func StoreNum(phoneList []PhoneRedisObj, expireInSecond int64) (err error) {
	ctx := context.Background()
	eg, _ := errgroup.WithContext(ctx)
	for _, phone := range phoneList {
		key := "phonestock:" + phone.Phone
		jsons, errs := json.Marshal(phone)
		if errs != nil {
			fmt.Println(errs.Error())
		}

		eg.Go(func() error {
			if expireInSecond != 0 {
				for _, resp := range global.ASIR_RedisDB.DoMulti(ctx, global.ASIR_RedisDB.B().JsonSet().Key(key).Path("$").Value(string(jsons)).Build(), global.ASIR_RedisDB.B().Expire().Key(key).Seconds(expireInSecond).Build()) {
					if err = resp.Error(); err != nil {
						panic(err)
					}
				}
			} else {
				err = global.ASIR_RedisDB.Do(ctx, global.ASIR_RedisDB.B().JsonSet().Key(key).Path("$").Value(string(jsons)).Build()).Error()
				if err != nil {
					panic(err.Error())
				}
			}
			return err
		})
	}
	eg.Wait()
	return nil
}
```
However, now I'm facing a new challenge. As the StoreNum is being called more and more frequently, the array length of the phoneList parameter in each API call for StoreNum is in the tens of thousands. This has led to:

1.The creation and destruction of goroutines consuming CPU and memory, lowering the overall performance of backend services;
2.Redis server CPU usage spiking due to the high concurrency brought by Pipelining and batch JSON.SET operations.

To solve these two problems, I tried to introduce a third-party library for goroutine pools: https://github.com/panjf2000/ants.git, to control the number of goroutines and reuse them. I've tried modifying the code as follows (not yet tested on real hardware):
```
func storePhone(phone PhoneRedisObj, wg *sync.WaitGroup, expireInSecond int64) {
	defer wg.Done()

	ctx := context.Background()
	key := "phonestock:" + phone.Phone
	jsons, errs := json.Marshal(phone)
	if errs != nil {
		fmt.Println(errs.Error())
	}

	if expireInSecond != 0 {
		for _, resp := range global.ASIR_RedisDB.DoMulti(ctx, global.ASIR_RedisDB.B().JsonSet().Key(key).Path("$").Value(string(jsons)).Build(), global.ASIR_RedisDB.B().Expire().Key(key).Seconds(expireInSecond).Build()) {
			if err := resp.Error(); err != nil {
				panic(err)
			}
		}
	} else {
		err := global.ASIR_RedisDB.Do(ctx, global.ASIR_RedisDB.B().JsonSet().Key(key).Path("$").Value(string(jsons)).Build()).Error()
		if err != nil {
			panic(err.Error())
		}
	}
}

func StoreNum(phoneList []PhoneRedisObj, expireInSecond int64) (err error) {
	wg := sync.WaitGroup{}
	wg.Add(len(phoneList))

	for _, phone := range phoneList {
		phone := phone
		err := global.ASIR_GoroutinePool.Submit(func() {
			storePhone(phone, &wg, expireInSecond)
		})

		if err != nil {
			fmt.Println("Error submitting task to pool:", err)
			wg.Done()
		}
	}

	wg.Wait()

	return nil
}

```
The type of global.ASIR_GoroutinePool is *ants.Pool, and the capacity of the goroutine pool is assumed to be set to 10,000.
`global.ASIR_GoroutinePool, err = ants.NewPool(10000)`

Assuming there are 2 StoreNum API requests sent to the server at the same time, the first API request has a phoneList length of 6,000, and the second API request has a phoneList length of 4,001. According to the working principle of ants.Pool, theoretically, it may happen that the first API request occupies 6,000 goroutines, and the second API request can only occupy the remaining 4,000 goroutines.

Based on the above assumptions, I have two questions for you:

1.Since the first API request has enough goroutines, will it be packaged into a single pipeline command and sent to the Redis server?
2.For the second API request, since the 4,000 goroutines it occupies are less than the length of the phoneList (4,001), will the assembly and sending of the pipeline be blocked until there are enough goroutines - that is, when the number of goroutines occupied by the second API request reaches 4,001 - before it's packaged into a single pipeline command and sent to the Redis server?

**Comment by rueian** [comment]
1. Actually, pipelining is not a Redis command. It is a technique of issuing multiple commands continuously without waiting for previous commands. rueidis will automatically pipeline all commands from your 10,000 concurrent goroutines to redis.
2. The pipeline will not be blocked unless your Redis is blocked. So after you get the first redis response from the first goroutine, your can then reuse it to serve your last item in the phoneList.

**Comment by dwzkit** [comment]
>
