### ISSUE TITLE
Cluster mode and MSet

### ISSUE THREAD

**Issue by lsgndln** [rueian/rueidis#190]
Hi, first of all thanks for the amazing work on this library.

I was wondering if there was a plan to have a `MSet` helper command similar to the `MGet`, that would work with the cluster client . (Fetching keys slots, then splitting into different commands etc...) If so, I would be interested and could help with a PR :)

In general, is using a pipeline faster/slower that MSET ? Thanks a lot

**Comment by rueian** [comment]
Hi @lsgndln,

Thank you for being so interested in contributions. However, I didn't notice your last edit in the comment until I finished these `MSet` helpers.

So, there will be `MSet` and `MSetNX` helpers in the release next week.

In general, MSET will be slightly faster than pipelining multiple SETs, very slightly.

**Comment by lsgndln** [comment]
Amazing thanks a lot. On a similar note, I just noticed another thing regarding the `MGet` helper. I am using a `hookClient` (for telemetry) and I have an issue with the helper.

It accept a `rueidis.Client` interface, which is great, but then in the code there is an assertion : 
```
if cc, ok := client.(*clusterClient); ok {
return clusterMGet(cc, ctx, cmds.MGets(keys), keys)
}
```
which fails because my client is not `clusterClient` but a `hookClient`.

Could the `clusterMGet` accept a `rueidis.Client` instead ?

**Comment by lsgndln** [comment]
Thank you very much 🥇
