### ISSUE TITLE
DragonflyDB 1.1.2: panic: protocol bug, message handled out of order

### ISSUE THREAD

**Issue by FZambia** [rueian/rueidis#195]
Hello:)

On local run came across:

```
panic: protocol bug, message handled out of order

goroutine 104 [running]:
github.com/rueian/rueidis.(*pipe)._backgroundRead(0xc000114120)
	/Users/fz/go/pkg/mod/github.com/rueian/rueidis@v0.0.90/pipe.go:425 +0x868
github.com/rueian/rueidis.(*pipe)._background(0xc000114120)
	/Users/fz/go/pkg/mod/github.com/rueian/rueidis@v0.0.90/pipe.go:228 +0x7e
created by github.com/rueian/rueidis.(*pipe).background.func1
	/Users/fz/go/pkg/mod/github.com/rueian/rueidis@v0.0.90/pipe.go:212 +0x5a
exit status 2
```

Also reproduces with DF v1.1.1 and v1.1.0

I think the issue caused by RESP3 support [added to DragonflyDB in v1.1.0](https://github.com/dragonflydb/dragonfly/releases/tag/v1.1.0).

DF now runs in Docker even on MacOS BTW (falling back to epoll where uring is not supported):

```
docker run -p 6379:6379 --rm -it docker.dragonflydb.io/dragonflydb/dragonfly:v1.1.2
```

**Comment by rueian** [comment]
Hi @FZambia,

Thank you for reporting the issue.

I have tried the new dragonfly. My initial investigation showed that this was caused by the different behavior of commands like PUBLISH between the new dragonfly and the original redis, and such difference could make this issue very hard to fix.

When the new dragonfly receives a command such as PUBLISH, it will produce 2 responses to the client:
1. an integer response.
2. a pubsub message to the destination channel

While the original redis only produces the later one.

**Comment by rueian** [comment]
Sorry, my previous comment is wrong. I am still investigating.

**Comment by rueian** [comment]
The cause was that the new dragonfly still uses RESP2, which is redis array, to deliver messages to channels. I think they should fix this behavior by using the '>' type of RESP3.

While on my side, I think I could only provide an option to force rueidis to use RESP2.

**Comment by rueian** [comment]
Ref: https://github.com/dragonflydb/dragonfly/issues/1052

**Comment by FZambia** [comment]
Many thanks for super quick response! I think having a way to force RESP2 would be a good thing in general. At least it will be a working workaround while DF have not fixed the protocol.

**Comment by rueian** [comment]
Hi @FZambia, the AlwaysRESP2 option has been added in v0.0.99. It is probably the last version before v1.

**Comment by FZambia** [comment]
@rueian many thanks, I'll definitely support it - I think such edge cases may happen from time to time with Redis-compatible backends.

May I ask some other question - `rueidis` currently uses go1.20 in `go.mod` - this prevents me from simply upgrading to it in Centrifuge library – since I promised to maintain last two minor Go versions, 1.19 and 1.20 at the moment. Wondering - was the change to 1.20 in rueidis `go.mod` required due to some feature or dependency?

**Comment by rueian** [comment]
The new `RedisMessage.AsBytes` introduced in v0.0.96 requires go1.20. (https://github.com/rueian/rueidis/commit/cebd383e628f86623c89961aa2510ea3e650194d)

**Comment by rueian** [comment]
I think it is possible to maintain a forked pre-release version, such as v0.0.99-go18, to exclude `RedisMessage.AsBytes` and stick to the old go version in the go.mod.

**Comment by FZambia** [comment]
Got it, thx.  Not sure it's a good idea to add hacks with build tags to `rueidis` just before v1 - so I'll bump in my lib I suppose.

**Comment by FZambia** [comment]
> I think it is possible to maintain a forked pre-release version, such as v0.0.99-go18, to exclude RedisMessage.AsBytes and stick to the old go version in the go.mod.

Or will do this way yep, switching to my fork for some time until go1.21. Thanks again!

**Comment by rueian** [comment]
Hi @FZambia, I have just uploaded the [v0.0.99-go1.18](https://github.com/rueian/rueidis/releases/tag/v0.0.99-go1.18).

**Comment by FZambia** [comment]
Ah, thanks a lot!

**Comment by FZambia** [comment]
@rueian sorry, when testing noticed that when using `AlwaysRESP2` client still sends `HELLO 3` during handshake - https://github.com/rueian/rueidis/blob/761a60ce65891e7dc9a0430eba783fb063e041ce/pipe.go#L108

From https://redis.io/commands/hello/:

> Clients that want to handshake using the RESP3 mode need to call the HELLO command and specify the value "3" as the protover argument

Looks like Rueidis should not send `3` right?

**Comment by rueian** [comment]
You are right. I am sorry that the `AlwaysRESP2` option is not being well tested.

I have filed a fix: https://github.com/rueian/rueidis/commit/edf4bda3b96cd95cac2a42ee4321b491e9808766.

**Comment by FZambia** [comment]
NP :) Just tested from the latest commit - looks good to me

**Comment by FZambia** [comment]
Many thanks, pinned to latest version! Also, let me share a thought about https://github.com/rueian/rueidis#supporting-go-mod-118 - I'd write there right from start when the support for go1.18 will be dropped in Rueidis. I suppose this will allow you to simplify dropping the maintenance of those release at some point in the future.

**Comment by rueian** [comment]
Hi @FZambia, Thanks for the great idea! I will add it to the README.
