### ISSUE TITLE
Cannot auth with password only

### ISSUE THREAD

**Issue by nerg4l** [rueian/rueidis#34]
Redis can be configured with `requirepass` which makes `AUTH` command accept a password without username. Currently, there is no option for this. `AUTH` command can only initiated with username and password.

Source: https://redis.io/commands/auth/

https://github.com/rueian/rueidis/blob/a525ad43300a4ea316a8ca1355a46752ee8be8ea/pipe.go#L73-L79

**Comment by rueian** [comment]
Hi @nerg4l,

Thank you for pointing it out.

In the new v0.0.45, it will use the `default` username if no username but password provided according to https://redis.io/commands/hello/

**Comment by nerg4l** [comment]
Thanks
