### ISSUE TITLE
Calls hang when redis stops

### ISSUE THREAD

**Issue by marcoreni** [rueian/rueidis#36]
- Spin up a server
- Start making non-blocking requests to that server
- Kill the server

At this point, the calls start to hang with variable timeouts, without respecting context deadlines. The issue seems to be inside this function: https://github.com/rueian/rueidis/blob/master/mux.go#L85 

The error returned is a ECONNREFUSED, the wire is nil, and the function just loops over the retry block.

I'm not proficient in Go, but AFAIU there is no context check inside that pipe function, so the behaviour is unpredictable.

Is there a way to catch this sooner and obtaining some sort of fail fast?

**Comment by marcoreni** [comment]
Hi @rueian , you are correct. We experienced this issue in AWS, where a master-slave cluster went into failover and rueidis was not able to recover the connection. We are still investigating that issue but we assumed that it was due to this (in that scenario, the cluster changes the IP, while maintaining the hostname)

**Comment by rueian** [comment]
Are you using Amazon MemoryDB or ElasticCache?
Could you provide the instructions on how you set up your AWS master-slave cluster and how you kill the master?
So that I could find a better way to handle this case.

**Comment by marcoreni** [comment]
We're using MemoryDB. The cluster has been created using the AWS GUI, general instance size, 1 shard and one replica per shard. The clients were on ECS, reaching the cluster via the cluster endpoint. 

The failover was generated scaling the cluster to a different instance size. Right now we're doing some further debugging to see if we can replicate using the "Failover primary" function of MemoryDB as well.

**Comment by rueian** [comment]
I have found the problem: During the scaling, MemoryDB will failover to a new redis instance with the same hostname.
But the same hostname causes rueidis to pick the old connection and enter the redirection loop.

I will fix the issue as soon as possible.

**Comment by rueian** [comment]
Hi @marcoreni,

I have updated some progress here: https://github.com/rueian/rueidis/pull/37

**Comment by rueian** [comment]
Hi @marcoreni,

The new version is released. Please let me know if it works for you!

**Comment by rueian** [comment]
I'll see what I can do. But actually, the cluster topology refresh rate of rueidis is faster than 1/s currently.

**Comment by rueian** [comment]
Hi @marcoreni, 

Unfortunately, after testing MemoryDB with `db.t4g.small` instance + 1 replica, I think it is hard to reduce the failover period from rueidis' side.

It really takes about 15~20 seconds to get the latest topology from the promoted replica after triggering a failover.

**Comment by rueian** [comment]
Hi @marcoreni,

I am going to close this issue. Feel free to reopen it if needed.
