### ISSUE TITLE
pass parameter to redisgraph query in golang

### ISSUE THREAD

**Issue by ebrahimtorabi** [rueian/rueidis#42]
hello.
how to pass nested struct as parameter to redisgraph query?

**Comment by rueian** [comment]
Hi @ebrahimtorabi, what query do you want to send?

**Comment by rueian** [comment]
You may need to construct the query string from your nested struct.

**Comment by ebrahimtorabi** [comment]
thanke you with reply.
i want to pass struct that contained list of other struct to query string and then 'UNWIND' this list ,then create my desired node by it
type TranslatedValue struct {
	Value    string `json:"value"`
	Language string `json:"language"`
}
type Record struct {
	Values    []TranslatedValue `json:"values"`
	Id string `json:"id"`
}

**Comment by rueian** [comment]
Is this what you are looking for? https://github.com/RedisGraph/RedisGraph/issues/784

**Comment by ebrahimtorabi** [comment]
thank you very much
In general, how to pass  parameter to rueidis.
please give me a example

**Comment by rueian** [comment]
Since the parameter here is a graph query, I am afraid that there is no general way to pass struct into a query.

For you case, I would recommended using the following approach:

```golang
package main

import (
	"context"
	"fmt"

	"github.com/rueian/rueidis"
)

type TranslatedValue struct {
	Value    string `json:"value"`
	Language string `json:"language"`
}

type Record struct {
	Values []TranslatedValue `json:"values"`
	Id     string            `json:"id"`
}

func (r *Record) BuildInsertQueries() []string {
	queries := []string{fmt.Sprintf("CREATE (:Record {id:'%s'})", r.Id)}
	for _, value := range r.Values {
		queries = append(queries, fmt.Sprintf("CREATE (:TranslatedValue {value:'%s', language:'%s'})", value.Value, value.Language))
		queries = append(queries, fmt.Sprintf("MATCH (r:Record),(t:TranslatedValue) WHERE r.id = '%s' AND t.value = '%s' AND t.language = '%s' CREATE (r)-[rl:HAS]->(t) RETURN rl", r.Id, value.Value, value.Language))
	}
	return queries
}

func main() {
	client, err := rueidis.NewClient(rueidis.ClientOption{InitAddress: []string{"127.0.0.1:6379"}})
	if err != nil {
		panic(err)
	}

	record := &Record{Id: "1", Values: []TranslatedValue{{Value: "vv", Language: "en"}}}

	for _, query := range record.BuildInsertQueries() {
		if err := client.Do(context.Background(), client.B().GraphQuery().Graph("records").Query(query).Build()).Error(); err != nil {
			panic(err)
		}
	}
}

```

**Comment by ebrahimtorabi** [comment]
thanks for your reply

**Comment by rueian** [comment]
I am going to close this issue. Feel free to reopen or open another issue if you need further help.
