### ISSUE TITLE
Can you provide sample code on how to use FtSearch and JsonSet

### ISSUE THREAD

**Issue by dwzkit** [rueian/rueidis#47]
Can you provide sample code on how to use FtSearch and JsonSet

**Comment by dwzkit** [comment]
Thank you for the example,I used the second example,It works.

JSON object (my_records:1:{
"key": "1",
"val": "my_value"
}) was successfully added to Redis, but failed when I tried to change the "key" field of "my_records:1" from "1" to "2" via json.set

My code is as follows
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/41875799/171005094-d5a91cd5-ec08-45eb-8c36-db835712e4f9.png">

Is there something wrong with the way I write?

**Comment by dwzkit** [comment]
I know why. It's fixed
	
if err := client.Do(ctx, client.B().JsonSet().Key("my_records:1").Path("$.key").Value("\"2\"").Build()).Error(); err != nil {
		panic(err)
	}

**Comment by rueian** [comment]
You could also use this:

```golang
client.B().JsonSet().Key("my_records:1").Path("$.key").Value(`"2"`).Build()
```

**Comment by dwzkit** [comment]
> Hi @dwzkit,
> 
> It is recommended using the `om` package to operate json records:
> 
> ```go
> package main
> 
> import (
> 	"context"
> 	"fmt"
> 
> 	"github.com/rueian/rueidis"
> 	"github.com/rueian/rueidis/om"
> )
> 
> type MyEntity struct { // define your own entity struct
> 	Key string  `json:"key" redis:",key"`
> 	Ver int64   `json:"ver" redis:",ver"`
> 	Val MyValue `json:"val"`
> }
> 
> type MyValue struct { // nested struct is also supported
> 	Name string `json:"name"`
> }
> 
> func main() {
> 	client, err := rueidis.NewClient(rueidis.ClientOption{InitAddress: []string{"127.0.0.1:6377"}})
> 	if err != nil {
> 		panic(err)
> 	}
> 	defer client.Close()
> 
> 	repo := om.NewJSONRepository("my_entity", MyEntity{}, client)
> 
> 	if err := repo.CreateIndex(context.Background(), func(schema om.FtCreateSchema) om.Completed {
> 		return schema.FieldName("$.val.name").Text().Build()
> 	}); err != nil {
> 		panic(err)
> 	}
> 
> 	entity := repo.NewEntity()  // initialize a new MyEntity, and
> 	entity.Val.Name = "my_name" // set its fields directly with the help of generics type inference
> 	if err = repo.Save(context.Background(), entity); err != nil {
> 		panic(err)
> 	}
> 	_, results, err := repo.Search(context.Background(), func(search om.FtSearchIndex) om.Completed {
> 		return search.Query("my_name").Build()
> 	})
> 	if err != nil {
> 		panic(err)
> 	}
> 	for _, entity := range results {
> 		fmt.Println(entity)
> 	}
> }
> ```
> 
> On the other hand, if you prefer handling details by yourself, here is an example:
> 
> ```go
> package main
> 
> import (
> 	"context"
> 	"encoding/json"
> 	"fmt"
> 	"strings"
> 
> 	"github.com/rueian/rueidis"
> )
> 
> type MyRecord struct {
> 	Key string `json:"key"`
> 	Val string `json:"val"`
> }
> 
> func main() {
> 	client, err := rueidis.NewClient(rueidis.ClientOption{InitAddress: []string{"127.0.0.1:6377"}})
> 	if err != nil {
> 		panic(err)
> 	}
> 	ctx := context.Background()
> 
> 	if err := client.Do(ctx, client.B().FtCreate().Index("my_records").OnJson().
> 		Prefix(1).Prefix("my_records:").Schema().FieldName("$.val").Text().Build()).Error(); err != nil {
> 		panic(err)
> 	}
> 
> 	if err := client.Do(ctx, client.B().JsonSet().Key("my_records:1").Path("$").Value(marshal(MyRecord{
> 		Key: "1",
> 		Val: "my_value",
> 	})).Build()).Error(); err != nil {
> 		panic(err)
> 	}
> 
> 	resp, err := client.Do(ctx, client.B().FtSearch().Index("my_records").Query("my_value").Build()).ToArray()
> 	if err != nil {
> 		panic(err)
> 	}
> 	for i := 1; i < len(resp); i += 2 {
> 		key, _ := resp[i+0].ToString()
> 		val, _ := resp[i+1].ToArray()
> 		var record MyRecord
> 		if err := val[1].DecodeJSON(&record); err != nil {
> 			panic(err)
> 		}
> 		fmt.Println(key, record)
> 	}
> }
> 
> func marshal(record MyRecord) string {
> 	sb := strings.Builder{}
> 	json.NewEncoder(&sb).Encode(record)
> 	return sb.String()
> }
> ```

I started trying to use the first method, but I don't know how to set the index name that already exists in RediSearch using om.NewJSONRepository.

```
// Create a new JSONRepository instance with the shared client
	jsonRepo := om.NewJSONRepository("phonestock", good_num.PhoneRedisObj{}, global.ASIR_RedisDB)

	// Search and retrieve search results
	_, searchResults, err := jsonRepo.Search(ctx, func(search om.FtSearchIndex) om.Completed {
		return search.Query(preSQL).Limit().OffsetNum(0, 16).Build()
	})

	if err != nil {
		log.Printf("Error retrieving previously ordered numbers: %v", err)
		return
	}
```

I need to set the Index Name of jsonRepo to phoneIndex, but phoneIndex already exists in the Redis server. How can I set an existing Index Name to jsonRepo?

**Comment by rueian** [comment]
Hi @dwzkit,

The index name of a json repo is fixed to jsonidx:reponame. You can’t change that.

https://github.com/rueian/rueidis/blob/189659f134a38c330739042c27c27b43f7a57c00/om/json.go#L124
