### ISSUE TITLE
How to make the response time of FT.Search as short as possible with 500 user requests per second?

### ISSUE THREAD

**Issue by dwzkit** [rueian/rueidis#48]
The service scenarios are as follows:
1. Each user request will result in 5-10 different ft.search queries
2. After querying the RedisJSON that meets the conditions, the JSON data need to be  modified
3. A maximum of 500 users may request the system at the same time per second

Go-redis(for exapmle:`res, err := r.Do("FT.SEARCH", "index", "@status:{0913|4912}", "LIMIT", 0, 1, "RETURN", 1, "$.Number").Result()`)is currently used to implement the above steps 1-2. Each user request opens a separate redis connection and the connection is disconnected at the end of steps 1-2.

Due to the excellent performance of RediSearch+RedisJSON, the average response time can be less than 200ms when there are only 5 to 10 user requests per second, but when there are more than 30~50 user requests per second, the average response time increases exponentially to 20 to 30 seconds. I think that redis is blocked because of the significant increase in the number of queries.

Can rueidis significantly reduce response time when QPS exceed 30 or even 300 to 500? What is the correct way to use Rueidis to meet the goal of minimizing response times for FT.Search queries?

**Comment by rueian** [comment]
In order to help you, I may need to know more about your scenario:

1. How does each user request result into 5-10 different ft.search queries? Does the 200ms latency you mentioned cover these ft.search?
2. Where the condition `@status:{0913|4912}` comes from? What json data need to be modified and how?

**Comment by dwzkit** [comment]
1.I store 100,000 JSON objects in reids
key:  data:2589148762910
value:

> {
>     "ID": "2589148762910",//The ID in each JSON object is different
>     "owner": "",
>     "ttlInSecond": 0,
>     "preOrderTime": 0,
>     "status": "2",
>     "prefixNum": "258",
>     "last4": "2910",
>     "last3": "910",
>     "include4": "true"
> }

2.`index_name is "daataIdx"`
> ft.info daataIdx
> index_name:daataIdx
> index_options:index_definition
> key_type:JSON
> prefixes:data:
> default_score1
> attributes
> identifier:$.ID
> attribute:id
> type:TEXT
> WEIGHT:1
> identifier:$.preOrderTime
> attribute:preOrderTime
> type:NUMERIC
> identifier:$.status
> attribute:status
> type:TAG
> SEPARATOR
> 
> identifier
> $.prefixNum
> attribute
> prefixNum
> type
> TAG
> SEPARATOR
> 
> identifier:$.last4
> attribute:last4
> type:TAG
> SEPARATOR
> 
> identifier:$.last3
> attribute:last3
> type:TAG
> SEPARATOR
> 
> identifier:$.include4
> attribute:include4
> type:TEXT
> WEIGHT:1
> 
> num_docs:133960
> max_doc_id:171685
> num_terms:133963
> num_records:1952961
> inverted_sz_mb:4.7424917221069336
> vector_index_sz_mb:0
> total_inverted_index_blocks:152632
> offset_vectors_sz_mb:0.70101642608642578
> doc_table_size_mb:12.264404296875
> sortable_values_size_mb:0
> key_table_size_mb:4.9214286804199219
> records_per_doc_avg:14.57868766784668
> bytes_per_record_avg:2.5463197231292725
> offsets_per_term_avg:0.37638694047927856
> offset_bits_per_record_avg:8
> hash_indexing_failures:0
> indexing:0
> percent_indexed:1
> gc_stats
> bytes_collected:1506014
> total_ms_run:526
> total_cycles:1
> average_cycle_time_ms:526
> last_run_time_ms:526
> gc_numeric_trees_missed:0
> gc_blocks_denied:0
> cursor_stats
> global_idle:0
> global_total:0
> index_capacity:128
> index_total:0

3.Each user request executes the following ft.Serach command:
keyWord is entered manually by the user,KeyWord1, keyWord2, keyWord3, keyWord4 values are not the same

> (1) r.Do("FT.SEARCH", "dataIdx",`@status:{1} @last4:{" + keyWord1 + "} @preOrderTime:[-inf " + strconv.FormatInt(time.Now().Unix()-30, 10) + "]`, "LIMIT", 0, 1, "RETURN", 1, "$.ID").Result()
> (2) r.Do("FT.SEARCH", "dataIdx",`@status:{1} @last3:{" + keyWord2 + "} @preOrderTime:[-inf " + strconv.FormatInt(time.Now().Unix()-30, 10) + "]`, "LIMIT", 0, 1, "RETURN", 1, "$.ID").Result()
> (3) r.Do("FT.SEARCH", "dataIdx",`@status:{1} @last4:{" + keyWord3 + "} @preOrderTime:[-inf " + strconv.FormatInt(time.Now().Unix()-30, 10) + "]`, "LIMIT", 0, 1, "RETURN", 1, "$.ID").Result()
> (4) r.Do("FT.SEARCH", "dataIdx",`@status:{1} @last3:{" + keyWord4 + "} @preOrderTime:[-inf " + strconv.FormatInt(time.Now().Unix()-30, 10) + "]`, "LIMIT", 0, 1, "RETURN", 1, "$.ID").Result()
> (5) r.Do("FT.SEARCH", "dataIdx","@include4:false", "LIMIT", 0, 1, "RETURN", 1, "$.ID").Result()

4.When a set of objects matching the search conditions is found, it is returned to the user and the value of the object is modified as follows
> r.Do("JSON.SET", keyPre+v, ".ttlInSecond", operatorkey.DEFAULT_TTL_INSECOND).Result()
> r.Do("JSON.SET", keyPre+v, ".owner", "\""+user.Uid+"\"").Result()
> r.Do("JSON.SET", keyPre+v, ".preOrderTime", timeNow).Result()

**Comment by rueian** [comment]
Hi @dwzkit, hope you are doing well.

Have you successfully minimized the response time of FT.Search queries?

**Comment by dwzkit** [comment]
Thank you very much for the reference code you gave me. I have tried according to the reference code, but the performance has not been significantly improved. I found that the bottleneck really is The Times of query of FT.

**Comment by dwzkit** [comment]
> I see. How often is your FT index changed? Maybe the performance could be improved via client-side caching.

Once the FT index is set, it basically does not change, except that the number of JSON objects stored increases

**Comment by rueian** [comment]
> > I see. How often is your FT index changed? Maybe the performance could be improved via client-side caching.
> 
> Once the FT index is set, it basically does not change, except that the number of JSON objects stored increases

Oh, that is what I mean of changed. FT index stores all objects inside one single redis key. Adding JSON objects or changing JSON objects will invalidate client side caching of the FT index.

**Comment by dwzkit** [comment]
> 
It is a pity that client Side Caching cannot be used if the data changes. In our business, users need to protect data after obtaining it to prevent it from being occupied by other users during the same period
