### ISSUE TITLE
JsonArrappend Fails to Append?

### ISSUE THREAD

**Issue by chayim** [rueian/rueidis#49]
I'm trying to use rueidis to manipulate arrays in a json object I've stored in redis:

```
json.set foo . '{"hello": "people", "colours": []}'
```

The following works within the redis-cli:

```
127.0.0.1:6379> JSON.ARRAPPEND foo $.colours '"red"'
1) (integer) 1
127.0.0.1:6379> JSON.ARRAPPEND foo $.colours '"blue"'
1) (integer) 2
127.0.0.1:6379> json.get foo $.colours
"[[\"red\",\"blue\"]]"
```

However, when using the library it appears to fail:

```
err := con.Do(ctx, con.B().JsonArrappend().Key("foo").Path("$.colours").Value("red").Build()).Error()
log.Fatal(err)
```
2022/06/07 15:09:48 expected value at line 1 column 1

It appears to fail, because the resulting string isn't quoted properly. Reproducing this in the console as below, you can see what happens when a string has double qutoes, but not the outer single quotes.

```
127.0.0.1:6379> JSON.ARRAPPEND foo .colours "red"
(error) expected value at line 1 column 1
```

The same is true for other operations.

**Comment by rueian** [comment]
Hi @chayim,
Yes, it is expected behavior of command builder. It doesn’t quote json string automatically. It just send what you send as redis string.

In your case, You can use the following way to send json string in redis string:

```golang
con.Do(ctx, con.B().JsonArrappend().Key("foo").Path("$.colours").Value(`"red"`).Build()).Error()
```

**Comment by chayim** [comment]
Hey @rueian agreed - I ran things throught fmt.Sprintf to format accordingly (other reasons). What do you think about either:

1. Supporting json quoted strings as expected
2. Updating the README to indicate this, for JSON commands.

I'm happy to contribute #2 if you're interested!

**Comment by chayim** [comment]
Perhaps a different bug... but the same json.arrappend when used repeatedly appears to add things twice. I admit this is unlikely - perhaps you can tell me what I'm doing wrong:

```
tagstr := fmt.Sprintf(`"%s"`, tag)
con.Do(ctx, con.B().JsonArrappend().Key("foo").Path("$.tags").Value(tagstr).Build())
```

At least on the redis side, it looks like the resulting array has each tag I've added twice, when iterating through this..

**Comment by rueian** [comment]
> Correct me if I'm wrong, but the OM case only makes sense if using the OM itself. In my case I'm opting for raw command usage.

I mean like this: https://go.dev/play/p/T2c35nUg-YD

> At least on the redis side, it looks like the resulting array has each tag I've added twice, when iterating through this..

I haven't reproduced that. Could you provide the full code?

**Comment by rueian** [comment]
Hi @chayim, I am going to close this issue. Feel free to create a new one if you want.
