### ISSUE TITLE
Is it safe to share a connection between goroutine to increment a common key?

### ISSUE THREAD

**Issue by ryan-netizen** [rueian/rueidis#5]
Hi, 

I wanted to ask one question, 

is it safe to use share same connection between multiple goroutines to increment a common(same) key without the worry that different goroutines incrementing the same key will result in an incorrect value?

I am using keydb(which is multithread) in the place of redis with this library.

Thanks for the great work.

**Comment by rueian** [comment]
Hi @ryan-netizen,

If you mean doing `INCR` like this, then yes. It is safe.

```golang
package main

import (
	"context"
	"sync"
	"github.com/rueian/rueidis"
)

const concurrency = 5000

func main() {
	ctx := context.Background()
	client, _ := rueidis.NewClient(rueidis.ClientOption{InitAddress: []string{"127.0.0.1:6379"}})

	wg := sync.WaitGroup{}
	wg.Add(concurrency)
	for i := 0; i < concurrency; i++ {
		go func() {
			_ = client.Do(ctx, client.B().Incr().Key("k").Build()).Error()
			wg.Done()
		}()
	}
	wg.Wait()

	count, _ := client.Do(ctx, client.B().Get().Key("k").Build()).AsInt64()
	// count == 5000
}
```

I have tested the above code with KeyDB 6.2.2. It worked.

Please feel free to share more detailed use case, so that I could help you.

**Comment by ryan-netizen** [comment]
@rueian Thanks for your reply. 

I was exactly trying to do the same thing but with hash field instead of a key. So with code with `rueidis` looks like below. 

And it works :)
```
package main

import (
	"context"
	"fmt"
	"sync"

	"github.com/rueian/rueidis"
)

const concurrency = 5000

func main() {
	ctx := context.Background()
	client, _ := rueidis.NewClient(rueidis.ClientOption{InitAddress: []string{"207.38.67.28:6479"}})
	defer client.Close()

	wg := sync.WaitGroup{}
	wg.Add(concurrency)
	for i := 0; i < concurrency; i++ {
		go func() {
			_ = client.Do(ctx, client.B().Hincrbyfloat().Key("h").Field("f").Increment(1).Build()).Error()
			wg.Done()
		}()
	}
	wg.Wait()

	count, _ := client.Do(ctx, client.B().Hget().Key("h").Field("f").Build()).AsFloat64()
	// count == 5000
}

``` 


But if i use `go-redis` client for the same operation it gives me inconsistent results. 
```
package main

import (
	"context"
	"fmt"
	"sync"

	"github.com/go-redis/redis/v8"
)

const concurrency = 5000

func main() {
	ctx := context.Background()
	rdb := redis.NewClient(&redis.Options{
		Addr:     "207.38.67.28:6479",
		Password: "", // no password set
		DB:       0,  // use default DB
	})
	defer rdb.Close()

	wg := sync.WaitGroup{}
	wg.Add(concurrency)
	for i := 0; i < concurrency; i++ {
		go func() {
			_ = rdb.HIncrByFloat(ctx, "h", "f", 1)
			wg.Done()
		}()
	}
	wg.Wait()

	count, _ := rdb.HGet(ctx, "h", "f").Float64()
	// count == 835
}
```

So, my question was does `rueidis` do some special locking that prevents data corruption? 

Thanks again for the Awesome library.

**Comment by rueian** [comment]
No, rueidis doesn't do any special locking in this case. It just sends commands to Redis or KeyDB.

It is also wired that go-redis get corrupted result. I think it might because some operations by go-redis were failed. Maybe you could check the value of `rdb.HIncrByFloat(ctx, "h", "f", 1).Err()` to verify that.

**Comment by ryan-netizen** [comment]
@rueian you were right. 
`go-redis` connection pooling was getting timed out and that missing err check made it difficult to capture. So thanks for the hint. After fixing that result was same. 

Last question, how does the auto-piping work in the cause of my above multiple `go-routines`? 

will `rueian` create one connection to send all the commands in the goroutines and in the end send exec?

Thanks

**Comment by rueian** [comment]
Yes, you almost get the answer. Except that it does't send `EXEC`, it just flush TCP buffer. 

This library will put non-blocking concurrent commands into a queue, then write them to one TCP buffer.

The TCP buffer will be flush either when the buffer is full or there is no further command to write.

**Comment by ryan-netizen** [comment]
Thanks, that was all I needed.
