### ISSUE TITLE
request for manual pipe

### ISSUE THREAD

**Issue by tsingson** [rueian/rueidis#50]
in my case, i need sync  a lots data to redis , from my db or csv.
so, it's need manual pipe.

i had test rueidis ( as default ) and go-redis v8 ( with pipe ) for 2K item import to redis,  v8 is more quick.

ps: thanks for great work in rueidis.

**Comment by rueian** [comment]
Hi @tsingson 

Have you tried `DoMulti` in the `rueidis.DedicatedClient`?

Here is an usage example : https://github.com/rueian/rueidis/blob/6acd2cbdc9e3bfab1bd55bd6db4bfb9c9592a91d/cmds.go#L20

Would you mind also provide your current code with rueidis and go-redis here?

**Comment by tsingson** [comment]
> https://github.com/rueian/rueidis#bulk-operations

thanks .
