### ISSUE TITLE
Connection degradation during PUB/SUB

### ISSUE THREAD

**Issue by FZambia** [rueian/rueidis#52]
Hello @rueian , I came across one more thing - spent some time trying to figure out - but failed.

I prepared a program that demonstrates a connection degradation while performing massive PUB/SUB:

<details>
  <summary>Go program</summary>
  
  ```go
package main

import (
	"context"
	"flag"
	"log"
	"runtime"
	"strconv"
	"sync/atomic"
	"time"

	"github.com/gomodule/redigo/redis"
	"github.com/rueian/rueidis"
)

var useRedigo = flag.Bool("redigo", false, "use redigo")
var numNodes = flag.Int("nodes", 200, "num nodes")

var (
	read        int64
	write       int64
	concurrency = runtime.NumCPU()
	data        = string(make([]byte, 512))
)

func main() {
	flag.Parse()

	go func() {
		var valRead int64
		var valWrite int64
		for {
			time.Sleep(time.Second)
			newValRead := atomic.LoadInt64(&read)
			newValWrite := atomic.LoadInt64(&write)
			log.Println(newValRead-valRead, "msg/sec read", newValWrite-valWrite, "msg/sec write")
			valWrite = newValWrite
			valRead = newValRead
		}
	}()

	if *useRedigo {
		runRedigo()
	} else {
		run()
	}
}

func run() {
	client, err := rueidis.NewClient(rueidis.ClientOption{
		InitAddress: []string{"127.0.0.1:6379"},
	})
	if err != nil {
		panic(err)
	}
	defer client.Close()

	messages := make(chan rueidis.PubSubMessage, 1024)
	var subscribeConns []rueidis.DedicatedClient

	for i := 0; i < *numNodes; i++ {
		conn, _ := client.Dedicate()

		conn.SetPubSubHooks(rueidis.PubSubHooks{
			OnMessage: func(m rueidis.PubSubMessage) {
				atomic.AddInt64(&read, 1)
				messages <- m
			},
		})

		resp := conn.Do(context.Background(), client.B().Subscribe().Channel("request", "response"+strconv.Itoa(i)).Build())
		if resp.Error() != nil {
			panic(resp.Error())
		}
		subscribeConns = append(subscribeConns, conn)
	}

	defer func() {
		for _, conn := range subscribeConns {
			conn.Close()
		}
	}()

	for i := 0; i < concurrency; i++ {
		go func() {
			for {
				client.Do(context.Background(), client.B().Publish().Channel("request").Message(data).Build())
				atomic.AddInt64(&write, 1)
				for i := 0; i < *numNodes; i++ {
					<-messages
					client.Do(context.Background(), client.B().Publish().Channel("response"+strconv.Itoa(i)).Message(data).Build())
					atomic.AddInt64(&write, 1)
				}
				for i := 0; i < *numNodes; i++ {
					<-messages
				}
			}
		}()
	}
	select {}
}

func runRedigo() {
	messages := make(chan redis.Message, 1024)
	var subscribeConns []redis.Conn

	for i := 0; i < *numNodes; i++ {
		c, err := redis.Dial("tcp", "127.0.0.1:6379",
			redis.DialReadTimeout(60*time.Second),
			redis.DialWriteTimeout(10*time.Second),
		)
		if err != nil {
			panic(err)
		}

		psc := redis.PubSubConn{Conn: c}

		// Start a goroutine to receive notifications from the server.
		go func() {
			for {
				switch n := psc.Receive().(type) {
				case error:
					panic(n)
				case redis.Message:
					atomic.AddInt64(&read, 1)
					messages <- n
				default:
				}
			}
		}()

		if err := psc.Subscribe("request", "response"+strconv.Itoa(i)); err != nil {
			panic(err)
		}

		subscribeConns = append(subscribeConns, c)
	}

	defer func() {
		for _, conn := range subscribeConns {
			_ = conn.Close()
		}
	}()

	for i := 0; i < concurrency; i++ {
		go func() {
			pubConn, err := redis.Dial("tcp", "127.0.0.1:6379",
				redis.DialReadTimeout(10*time.Second),
				redis.DialWriteTimeout(10*time.Second))
			if err != nil {
				panic(err)
			}
			defer func() { _ = pubConn.Close() }()
			for {
				_, err := pubConn.Do("PUBLISH", "request", data)
				if err != nil {
					panic(err)
				}
				atomic.AddInt64(&write, 1)
				for i := 0; i < *numNodes; i++ {
					<-messages
					_, _ = pubConn.Do("PUBLISH", "response"+strconv.Itoa(i), data)
					atomic.AddInt64(&write, 1)
				}
				for i := 0; i < *numNodes; i++ {
					<-messages
				}
			}
		}()
	}
	select {}
}
  ```
  
</details>

This program implements sort of request-reply pattern on top of PUB/SUB (actually a bit artificial, but reproduces an issue for me).

The problem is that with `rueidis` connection degrades very quickly - Go process starts consuming all the CPU on machine, CPU profile shows 96% of `runtime.gosched_m`. Redis is mostly not loaded at this time - maybe 2-3% of CPU usage.  The same program with Redigo does not have such a problem.

So for me the output for `rueidis` (`go run main.go`) case is sth like:

```
2022/06/15 22:13:16 179939 msg/sec read 90400 msg/sec write
2022/06/15 22:13:17 33935 msg/sec read 17191 msg/sec write
2022/06/15 22:13:18 14225 msg/sec read 7059 msg/sec write
2022/06/15 22:13:19 2098 msg/sec read 1092 msg/sec write
2022/06/15 22:13:20 2430 msg/sec read 1068 msg/sec write
2022/06/15 22:13:21 1569 msg/sec read 1140 msg/sec write
2022/06/15 22:13:22 2920 msg/sec read 960 msg/sec write
...
```

And for Redigo (`go run main.go -redigo`) PUB/SUB is stable all the time:

```
2022/06/15 22:13:49 125744 msg/sec read 62837 msg/sec write
2022/06/15 22:13:50 119642 msg/sec read 60334 msg/sec write
2022/06/15 22:13:51 122295 msg/sec read 61811 msg/sec write
2022/06/15 22:13:52 127341 msg/sec read 63667 msg/sec write
2022/06/15 22:13:53 124588 msg/sec read 62681 msg/sec write
2022/06/15 22:13:54 123669 msg/sec read 62178 msg/sec write
2022/06/15 22:13:55 123225 msg/sec read 61936 msg/sec write
...
```

I am on Darwin (MacOS), Redis 6.2.1, go version go1.18.3 darwin/amd64

Not 100% sure you will be able to reproduce an issue on your machine - maybe increase  `concurrency` or `nodes`.

**Comment by rueian** [comment]
Hi @FZambia,

I will look into the CPU usage issue and how does redigo work later today.

Just a quick reply for the pubsub degradation:
Since you aggregate all messages into one channel and you also publish new message to it while consuming it, 1024 buffer is probably not enough.

Could you try using `messages := make(chan rueidis.PubSubMessage, (numNodes+numNodes)* concurrency)`?

**Comment by FZambia** [comment]
> Could you try using messages := make(chan rueidis.PubSubMessage, (numNodes+numNodes)* concurrency)?

Thanks! Just tried – this fixes triggering a bad state, but seems like a workaround for some underlying problem anyway. In real-life I can not guess the buffer size on start.

**Comment by FZambia** [comment]
Thanks!

> Dialer: net.Dialer{KeepAlive: -1},

I tried this – it fixes the behaviour in example program, but in real benchmark I have I still get the behavior with 96% Goshed, not sure what's the difference - but I suppose the issue is not only in that background goroutine 🤔

**Comment by rueian** [comment]
Hi @FZambia,

The new v0.0.56 is released and the CPU usage issue should be fixed.

Previously, the background writer routine in `pipe` would keep busy looping if there were undelivered responses. And the small buffer in your case made the loop become longer.

The reason why setting `Dialer: net.Dialer{KeepAlive: -1}` in the above example case worked is that the background ping routine is the only one who sends commands. Once disabled, the background writer could go to sleep.

In v0.0.56, [this commit](https://github.com/rueian/rueidis/commit/e5e020c1f4d52b8b84f3a0289ab2a0784e7e84ef) put the background writer into sleep immediately if there are no more commands to send and has nothing to do with undelivered responses.

This is rueidis v0.0.56 on my Macbook M1 Pro with local Redis v7
<img width="611" alt="image" src="https://user-images.githubusercontent.com/2727535/174446010-e7e9af0d-db47-40f2-a026-6eeace64f318.png">

This is redigo v1.8.8 on my Macbook M1 Pro with local Redis v7
<img width="608" alt="image" src="https://user-images.githubusercontent.com/2727535/174446112-65292a78-5343-405f-bf4e-9664065280f8.png">

Please let me know if the new version works for you.

**Comment by FZambia** [comment]
Just tried v0.0.57 – don't experience CPU issues now, works stable. CPU consumption of Go process is less than in Redigo's case while throughput is better. Many thanks again for your time and help! 💪

**Comment by rueian** [comment]
Thanks! Glad to hear that.

Then I am going to close this issue. Please open a new one if you want. I am willing to help.
