### ISSUE TITLE
Connection close not detected and deadlock on acquire

### ISSUE THREAD

**Issue by FZambia** [rueian/rueidis#54]
Hello, me again with a couple of new issues. 

New program which demonstrates a couple of issues with `rueidis`.

```go
package main

import (
	"flag"
	"log"
	"time"

	"github.com/gomodule/redigo/redis"
	"github.com/rueian/rueidis"
)

var useRedigo = flag.Bool("redigo", false, "use redigo")

func main() {
	flag.Parse()
	if *useRedigo {
		runRedigo()
	} else {
		run()
	}
}

func run() {
	client, err := rueidis.NewClient(rueidis.ClientOption{
		InitAddress: []string{"127.0.0.1:6379"},
	})
	if err != nil {
		panic(err)
	}
	defer client.Close()

	for {
		log.Println("start pub/sub")
		conn, _ := client.Dedicate()
		wait := conn.SetPubSubHooks(rueidis.PubSubHooks{
			OnMessage: func(m rueidis.PubSubMessage) {

			},
		})
		log.Println("pub/sub is ready")
		err := <-wait
		log.Println("pub/sub error", err)
		conn.Close()
		time.Sleep(1 * time.Millisecond)
	}
}

func runRedigo() {
	pool := &redis.Pool{
		Dial: func() (redis.Conn, error) {
			return redis.Dial("tcp", "127.0.0.1:6379",
				redis.DialReadTimeout(60*time.Second),
				redis.DialWriteTimeout(10*time.Second),
			)
		},
	}

LOOP:
	for {
		log.Println("start pub/sub")
		conn := pool.Get()
		psc := redis.PubSubConn{Conn: conn}

		log.Println("pub/sub is ready")

		for {
			switch n := psc.Receive().(type) {
			case error:
				log.Println("pub/sub error", n)
				_ = conn.Close()
				time.Sleep(1 * time.Millisecond)
				continue LOOP
			default:
			}
		}
	}
}
```

## Problem 1

1. Run Redis
2. Run program above
3. Stop Redis

Redigo-based program detects connection close and goes to reconnect loop, Rueidis-based program does not.

Looks like Rueidis detects connection close only upon the next write operation.

## Problem 2

I added a periodic write to help Rueidis finding a broken connection after stopping Redis. It goes to reconnect loop – but at some point (very quickly and I can reliably reproduce this every time) it deadlocks on connection acquire (inside `client.Dedicate()` call) – so reconnecting stops. Redigo-based program does not have this issue.

From the goroutine dump of deadlocked-program:

```
goroutine 1 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0xc000074110, 0x0)
	/usr/local/Cellar/go/1.18.3/libexec/src/runtime/sema.go:513 +0x13d
sync.(*Cond).Wait(0xc00007e080?)
	/usr/local/Cellar/go/1.18.3/libexec/src/sync/cond.go:56 +0x8c
github.com/rueian/rueidis.(*pool).Acquire(0xc00007e230)
	/Users/fz/go/pkg/mod/github.com/rueian/rueidis@v0.0.57/pool.go:31 +0x45
github.com/rueian/rueidis.(*mux).Acquire(0x10b8650?)
	/Users/fz/go/pkg/mod/github.com/rueian/rueidis@v0.0.57/mux.go:208 +0x1d
github.com/rueian/rueidis.(*singleClient).Dedicate(0xc00000e1b0)
	/Users/fz/go/pkg/mod/github.com/rueian/rueidis@v0.0.57/client.go:73 +0x2d
main.run()
	/Users/fz/projects/centrifugal/centrifugo-pro/internal/pro/redengine/exp/main.go:35 +0x1fb
main.main()
	/Users/fz/projects/centrifugal/centrifugo-pro/internal/pro/redengine/exp/main.go:20 +0x72
```

**Comment by rueian** [comment]
Hi @FZambia,

For the problem 2, I suspect that is because reaching the maximum connection pool size.

Do you call the second returned value from the `Dedicate`? It is a callback function that will reduce the pool size counter.

**Comment by FZambia** [comment]
> Do you call the second returned value from the Dedicate? It is a callback function that will reduce the pool size counter.

Oh, good to know – just tried and it now works fine. Do you think it makes sense to automatically call cancel if `conn.Close` for `Dedicated` was called?

**Comment by rueian** [comment]
> Oh, good to know – just tried and it now works fine. Do you think it makes sense to automatically decrement the counter if `conn.Close` for `Dedicated` was called?

Good idea. Just release a new v0.0.58 and it will automatically decrement the counter. Problem 1 is also fixed.

**Comment by FZambia** [comment]
So so cool, thanks a lot, just tested it – works!
