### ISSUE TITLE
How to perform FT.AGGREGATE?

### ISSUE THREAD

**Issue by Delicious-Bacon** [rueian/rueidis#57]
I have built the `om.NewJSONRepository` and with it, I can perform
```
repo.Search(ctx, func(schema om.FtSearchIndex) om.Completed {
        return schema.Query(...).Build()
})
```
But that's just the `FT.SEARCH` command. I need the `FT.AGGREGATE` functionality—is there a way to do that?

**Comment by rueian** [comment]
Hi @Delicious-Bacon,

Currently, the OM pkg doesn't provide `FT.AGGREGATE` interface, because I didn't figure out how to deal with the free style responses from the `FT.AGGREGATE`.

Now, you have to do `FT.AGGREGATE` by specifying the index name and handle the response manually:
```golang
client.Do(context.Background(), client.B().FtAggregate().Index("jsonidx:"+prefix).Query(...).Build())
```

Any suggestions and proposals are welcome.

**Comment by Delicious-Bacon** [comment]
Hello, @rueian!

Two things I've noticed with the `FtAggregate()`:
1. I cannot chain the aggregate functions. GROUPBY -> REDUCE -> SORTBY -> GROUPBY will not work, and it works in Redis (tested in Redis 7).
Redis CLI example:
```
FT.AGGREGATE books @loc:{1} GROUPBY 1 @id REDUCE MIN 1 @count as minCount SORTBY 2 @minCount ASC GROUPBY 1 @id
```
rueidis:
```
FtAggregate().Index("books").Query("@loc{1}").
Groupby(1).Property("@appID").
Reduce("MIN").Nargs(1).Arg("@count").As("minCount").
Sortby(2).Property("@price").Asc().
Groupby() // this fails
```
Linter error:
```
undefined (type cmds.FtAggregateSortbyFieldsOrderAsc has no field or method Groupby)compiler[MissingFieldOrMethod](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal?utm_source%3Dgopls#MissingFieldOrMethod)
```
2. I don't know how to handle the returned values. The only thing that resembles the result from the Redis CLI is `.ToAny()`, `[1 [id 1 minCount 12]]`. But how do I extract any information out of it? If I do `.ToArray()` I get gibberish. 🤷‍♂️

**Comment by rueian** [comment]
Hi @Delicious-Bacon,

The command builder is generated from [this](https://github.com/RediSearch/RediSearch/blob/32113de603deb21f4e0ed7ac1254d64c186c8f5f/commands.json#L1131). It only allows `GROUPBY->REDUCE` -> `GROUPBY->REDUCE` -> `SORTBY`.

And the syntax is the same as [the document](https://redis.io/docs/stack/search/reference/aggregations/#aggregate-request-format):
<img width="747" alt="image" src="https://user-images.githubusercontent.com/2727535/177004045-496833b6-e2cf-4ff2-a53f-4b2574838e76.png">

Be careful. It seems that the document doesn't guarantee the sorting order will remain the same after successive `GROUPBY`.

However, you can still use the `Arbitrary` builder to build a command that can't be built by the command builder, for example: `c.B().Arbitrary("FT.AGGREGATE").Keys("myidx").Args("...", "...", "...").Build()`

---

Here is a full example showing how to use OM and handle the response of `FT.AGGREGATE`:

```golang
package main

import (
	"context"
	"fmt"
	"github.com/rueian/rueidis"
	"github.com/rueian/rueidis/om"
)

type Book struct {
	Key   string   `json:"key"   redis:",key"`
	Ver   int64    `json:"ver"   redis:",ver"`
	ID    int64    `json:"id"    redis:",id"`
	Count int64    `json:"count" redis:",count"`
	Loc   []string `json:"loc"   redis:",loc"`
}

func main() {
	client, err := rueidis.NewClient(rueidis.ClientOption{InitAddress: []string{"127.0.0.1:6377"}})
	if err != nil {
		panic(err)
	}
	defer client.Close()

	ctx := context.Background()

	repo := om.NewJSONRepository("books", Book{}, client)
	if err := repo.CreateIndex(ctx, func(schema om.FtCreateSchema) om.Completed {
		return schema.
			FieldName("$.id").As("id").Numeric().
			FieldName("$.loc.*").As("loc").Tag().
			FieldName("$.count").As("count").Numeric().Sortable().Build()
	}); err != nil {
		panic(err)
	}

	for i := 0; i < 10; i++ {
		book := repo.NewEntity()
		book.ID = int64(i / 2)
		book.Count = int64(i)
		book.Loc = []string{"1"}
		if err := repo.Save(ctx, book); err != nil {
			panic(err)
		}
	}

	response, err := client.Do(context.Background(),
		client.B().FtAggregate().Index("jsonidx:books").Query("@loc:{1}").
			Groupby(1).Property("@id").Reduce("MIN").Nargs(1).Arg("@count").As("minCount").
			Sortby(2).Property("@minCount").Asc().Build(),
	).ToArray()
	if err != nil {
		panic(err)
	}

	fmt.Print("Number of records returned: ")
	fmt.Println(response[0].ToInt64())

	for _, record := range response[1:] {
		r, err := record.AsStrMap()
		if err != nil {
			panic(err)
		}
		fmt.Println("record", r["id"], r["minCount"])
	}
}

```

**Comment by Delicious-Bacon** [comment]
[Docs example](url) also shows an example of `APPLY -> GROUPBY [REDUCE] -> SORTBY` which is also not possible with rueidis. There's also `APPLY -> GROUPBY [REDUCE] -> SORTBY -> APPLY` example just above.

I couldn't find an example of `GROUPBY [REDUCE] -> SORTBY -> GROUPBY` but I am waiting for the response on Redis Discord channel.
<hr>
Thank you for the wonderful example of `FT.AGGREGATE`! ❤️

**Comment by rueian** [comment]
> [Docs example](url) also shows an example of `APPLY -> GROUPBY [REDUCE] -> SORTBY` which is also not possible with rueidis. There's also `APPLY -> GROUPBY [REDUCE] -> SORTBY -> APPLY` example just above.
> 
> I couldn't find an example of `GROUPBY [REDUCE] -> SORTBY -> GROUPBY` but I am waiting for the response on Redis Discord channel.

Hi @Delicious-Bacon,

I have update v0.0.60, which is now able to freely compose those operations with FtAggregate command builder.

The `om.Repository` also has `Aggregate` method now, you can use it as bellow example:

```golang
	cursor, err := repo.Aggregate(context.Background(), func(search om.FtAggregateIndex) om.Completed {
		return search.Query("@loc:{1}").
			Groupby(1).Property("@id").Reduce("MIN").Nargs(1).Arg("@count").As("minCount").
			Sortby(2).Property("@minCount").Asc().Build()
	})

	for {
		result, err := cursor.Read(context.Background())
		if err == om.EndOfCursor {
			break
		}
		if err != nil {
			panic(err)
		}
		for _, record := range result {
			fmt.Println("record", record["id"], record["minCount"])
		}
	}
```
