### ISSUE TITLE
Dynamic cmd building

### ISSUE THREAD

**Issue by Delicious-Bacon** [rueian/rueidis#59]
Hey, @rueian !

Is it possible to do dynamic `cmd` building depending on code logic?

Here's an example of what I'm trying to do:

```
// q is struct with query fields

cmd := client.B().FtAggregate().
    Index("books").Query("@genre:{" + q.Genre+ "}").
    Groupby(1).Property("@title")

// now I need to do conditional logic
// and continue building the cmd

if q.SortAsc {
    cmd = cmd.Sortby(2).Property(q.SortProperty).Asc() // but this won't work*
} else {
    cmd = cmd.Sortby(2).Property(q.SortProperty).Desc()
}
```
* the reason it doesn't work is because `cmd` is of type `cmds.FtAggregateOpGroupbyProperty` so I cannot change it anymore.

Also, since the `cmds` package is internal, I cannot initialize a variable of the final "chain" type I want to then assign the first `cmd` with chained methods to that final variable. For example:

```
var finalCmdDesc cmds.FtAggregateOpSortbyFieldsOrderDesc
var finalCmdAsc cmds.FtAggregateOpSortbyFieldsOrderAsc

// ...

if q.SortAsc {
    finalCmdAsc = cmd.Sortby(2).Property(q.SortProperty).Asc()
} else {
    finalCmdDesc = cmd.Sortby(2).Property(q.SortProperty).Desc()
}
```
Even with that, I would need additional bool flags to know which one to use in the end. 😅 
Or I could use generics... 🤔

**Comment by rueian** [comment]
Hi @Delicious-Bacon,

If the q.SortAsc is the only variant, I recommend use this:
```go
var resp rueidis.RedisResult
if q.SortAsc {
    resp = client.Do(ctx, cmd.Asc())
} else {
    resp = client.Do(ctx, cmd.Desc())
}
```

Otherwise, I think `client.B().Arbitrary()` will be a better choice.

**Comment by Delicious-Bacon** [comment]
> If the q.SortAsc is the only variant, I recommend use this:

It is not the only variant, but I can manage something with that. Thanks!

I'll close this issue.
