### ISSUE TITLE
Redis Sentinel support

### ISSUE THREAD

**Issue by FZambia** [rueian/rueidis#6]
Hello @rueian. Just came across `rueidis` in the Go weekly mailing list. Many thanks for the library, great job. Decisions made on API look really nice.

One thing that is missing for me to painlessly try this lib in my projects is the lack of Redis Sentinel support. Do you have plans to support Sentinel inside `rueidis`? Or maybe as a separate library built on top of `rueidis`?

**Comment by rueian** [comment]
Hi @FZambia,

I think I could support Sentinel inside this library. Let me take some time to figure it out.

**Comment by rueian** [comment]
Hi @FZambia,

I have released a new version that supports sentinel.

Please let me know if there is any issue when using this library. I would be glad to solve that.

**Comment by FZambia** [comment]
@rueian uff - that was super quick. Thanks!

One thing I noticed in Sentinel support pr is that atomic is not placed to the top of the struct which may fail on 32-bit archs as mentioned [here](https://pkg.go.dev/sync/atomic#pkg-note-BUG). Seems like you followed this for existing structs but not for `sentinelClient` struct.

One more thing I noticed is the lack of `ReadTimeout` and `WriteTimeout` control for the connection. Maybe missed sth – but I only found dial timeout.

Closing - thanks again, I'll definitely follow the development of this lib.

**Comment by rueian** [comment]
> @rueian uff - that was super quick. Thanks!
> 
> One thing I noticed in Sentinel support pr is that atomic is not placed to the top of the struct which may fail on 32-bit archs as mentioned [here](https://pkg.go.dev/sync/atomic#pkg-note-BUG). Seems like you followed this for existing structs but not for `sentinelClient` struct.
> 

I do aware the alignment requirement, but I just thought it was only required by 64bit atomic operation. Thank you for pointing it out. I will have a deeper look on that.

> One more thing I noticed in `rueidis` is the lack of `ReadTimeout` and `WriteTimeout` control for the connection. Maybe missed sth – but I only found dial timeout.
> 

Yes, you are right. Currently there is no `ReadTimeout` and `WriteTimeout` because I am not quite sure what they could provide to users.

One common use case I know is to abort operations under network issue or a server who stop to ack packet. I think this case can be handled by tcp keepalive.

Could you share more insights about the `ReadTimeout` and `WriteTimeout`?

> Closing - thanks again, I'll definitely follow the development of this lib.

@FZambia, You are welcome!

**Comment by FZambia** [comment]
> One common use case I know is to abort operations under network issue or a server who stop to ack packet. I think this case can be handled by tcp keepalive.

TCP keepalives is the mechanism to maintain connection open and detect broken ones on TCP level. But what I mean is to prevent op blocking for a long time by setting read and write deadlines to the connection. Analogous to https://github.com/go-redis/redis/blob/v8.11.4/options.go#L74

**Comment by rueian** [comment]
I see.

However, in my opinion, supporting context cancellation is better than setting tcp timeout for the purpose of preventing op blocking for a long time.

Supporting context cancellation is also very hard. It may also take some time to find a performant way to implement.

**Comment by FZambia** [comment]
I think you may have both. Context is nice but it may really hit performance.

**Comment by rueian** [comment]
I have tried a naive approach like this:

```golang
ch := make(chan RedisResult, 1)
go func() { ch <- c.Client.Do(ctx, cmd) }()
select {
    case <-ctx.Done():
        return newErrResult(ctx.Err())
    case resp = <-ch:
        return resp
}
```

Yes, the performance was really bad. It cost additional 500ns on every operations.

I am also trying the tcp timeout approach. It is also very difficult with the auto pipeline. 
While setting `WriteDeadline` on net.TCPConn is fairly easy, I still not figured out how to handle the `ReadDeadline` error.

**Comment by rueian** [comment]
Hi @FZambia,

I just figured out how to support context cancellation with minimum and optional overhead.

Please take a look if you are interested in the feature: https://github.com/rueian/rueidis/pull/7
