### ISSUE TITLE
How to implement TS.RANGE ... ALIGN - in rueidis

### ISSUE THREAD

**Issue by AlexanderJLiu** [rueian/rueidis#62]
https://redis.io/commands/ts.range/

![image](https://user-images.githubusercontent.com/15494997/178988755-9206c77b-af0f-4f60-8602-72297849d1a9.png)

Now, rueidis only support Align int64 value, can we support - or + as well?

**Comment by AlexanderJLiu** [comment]
Thanks for such a quick reply, got it.

**Comment by rueian** [comment]
Hi @AlexanderJLiu,

`ALIGN` now accepts string argument in v0.0.61

**Comment by AlexanderJLiu** [comment]
Great!!! So quick !!!👍
