### ISSUE TITLE
How to set the expire period for json key? Can you provide reference code

### ISSUE THREAD

**Issue by dwzkit** [rueian/rueidis#63]
How to set the expire period for json key? Can you provide reference code

**Comment by rueian** [comment]
Hi @dwzkit, 

Does the EXPIRE command work for you?

**Comment by dwzkit** [comment]
> Hi @dwzkit,
> 
> Does the EXPIRE command work for you?

yes,It can work

`err = repo.db.Do(ctx, repo.db.B().Expire().Key(key).Seconds(expireInSecond).Build()).Error()`
