### ISSUE TITLE
Can the redis JSON value be converted into struct+map form?

### ISSUE THREAD

**Issue by dwzkit** [rueian/rueidis#64]
Value Example in Redis as fllows:
```
{
   "Uid":"xxx",
   "Phone":"139xxxxxxxxx",
   "hobit":{
        "swimming":"yes",
        "running":"yes",
        "football":"yes",
    }
}
```

Want to get redis json value from redis server like above,then converted into struct+map form like bellow:
```
type T struct {
	Uid   string `json:"Uid"`
	Phone string `json:"Phone"`
	Hobit map[string]interface{} `json:"hobit"`
}
```

Is there a function that can handle this?

**Comment by rueian** [comment]
> Value Example in Redis as fllows:
> 
> ```
> {
>    "Uid":"xxx",
>    "Phone":"139xxxxxxxxx",
>    "hobit":{
>         "swimming":"yes",
>         "running":"yes",
>         "football":"yes",
>     }
> }
> ```
> 
> Want to get redis json value from redis server like above,then converted into struct+map form like bellow:
> 
> ```
> type T struct {
> 	Uid   string `json:"Uid"`
> 	Phone string `json:"Phone"`
> 	Hobit map[string]interface{} `json:"hobit"`
> }
> ```
> 
> Is there a function that can handle this?

Hi @dwzkit, I believe this can do the conversion for you https://github.com/rueian/rueidis/blob/21e43ebc5d7a7a5ec0f0c50fc572caf0b7b67d92/message.go#L154

**Comment by dwzkit** [comment]
> 

yes, DecodeJSON can help me do the job,Thanks!
