### ISSUE TITLE
Obtain a non-existent key using JSONGet through Client Side Caching 

### ISSUE THREAD

**Issue by dwzkit** [rueian/rueidis#67]
`var resp = repo.db.DoCache(ctx, repo.db.B().JsonGet().Key(key).Paths("$"+"."+searchOption.Province+"."+searchOption.City).Cache(), 720*time.Hour)`

How to decode the resp to make sure the key doesn't exist?

**Comment by rueian** [comment]
Hi @dwzkit,

`JSON.GET` will return a Redis Nil message when the key does not exist.

Therefore, if `rueidis.IsRedisNil(err) == true` then you can conclude the key does not exist:

```
if err := client.DoCache(ctx, client.B().JsonGet().Key("key").Paths("$").Cache(), time.Minute).DecodeJSON(...); err != nil {
	if rueidis.IsRedisNil(err) {
		// key doesn't exist
	}
}
