### ISSUE TITLE
How to create a key using JSONSet when it does not exist

### ISSUE THREAD

**Issue by dwzkit** [rueian/rueidis#68]
I need to create a key using JSONSet when it does not exist

`err :=repo.db.Do(ctx, repo.db.B().JsonSet().Key(key).Path("$."+searchOption.Province).Value(string(jsons)).Build()).Error()`

But failed, err message as follow
“ERR new objects must be created at the root”

How to create a key using JSONSet when it does not exist?

**Comment by rueian** [comment]
Hi @dwzkit,

As the error suggests, you can only use `$` as the path if the key does not exist.
