### ISSUE TITLE
bug in rueidis/binary.go

### ISSUE THREAD

**Issue by bundleman** [rueian/rueidis#72]
Hi!
"Any" doesn't exists type https://github.com/rueian/rueidis/blob/6517919074ccc7663f8354fbe7367c153f729129/binary.go#L20

Also take a look at https://github.com/json-iterator/go instead of the standard lib.

**Comment by rueian** [comment]
> Hi! "Any" doesn't exists type
> 
> https://github.com/rueian/rueidis/blob/6517919074ccc7663f8354fbe7367c153f729129/binary.go#L20

Hi @bundleman, please use go 1.18.

**Comment by bundleman** [comment]
> > Hi! "Any" doesn't exists type
> > https://github.com/rueian/rueidis/blob/6517919074ccc7663f8354fbe7367c153f729129/binary.go#L20
> 
> Hi @bundleman, please use go 1.18.
Ok. Thanks

**Comment by avi94** [comment]
@rueian Hi. Why is it an absolute requirement to use 1.18? And is it documented anywhere to use 1.18 or above?

**Comment by rueian** [comment]
Hi @avi94,

It is the Generic OM that requires 1.18 https://github.com/rueian/rueidis#generic-object-mapping
