### ISSUE TITLE
new feat for rueidis

### ISSUE THREAD

**Issue by xiluoxi** [rueian/rueidis#75]
expect to return normally when there is an error occurs(no redis error,example: eof) in the query redis, no keep retry.

**Comment by rueian** [comment]
Hi @xiluoxi,

Implement no retry is quite simple. I can implement it in couples of days.

But I am curious about the reason why you don’t want auto retry?

**Comment by xiluoxi** [comment]
> If the redis service is disconnected, the processing flow will be blocked due to the retry mechanism. At the same time, in a service with high concurrency, a large number of blocked processes will lead to increased memory pressure, and my service may down as a result.So,I hope that the retry mechanism can be cancelled through configuration

**Comment by rueian** [comment]
Actually, the client will stop retry if the ctx is cancelled. Is this not enough in your case?

**Comment by xiluoxi** [comment]
> Actually, the client will stop retry if the ctx is cancelled. Is this not enough in your case?
But in this way, I don't know the result of call redis.
Also, as a caller, I don't know when to cancel CTX. Because the method didn't give me any results

**Comment by rueian** [comment]
Hi @xiluoxi,

Normally, you will use context.WithTimeout or rely on upper level framework to cancel the ctx automatically

**Comment by xiluoxi** [comment]
Ok, this will solve the problem of blocking, thanks.

**Comment by xiluoxi** [comment]
But in this case, How to get the error of querying redis?
@rueian

**Comment by rueian** [comment]
I am hard to imagine what you want to do with network errors in this case. Could you give me some examples?

rueidis already keep trying to reconnect to redis automatically if network errors.

**Comment by xiluoxi** [comment]
> It is hard for me to imagine what you want to do with network errors in this case. Could you give me some examples?
> 
> Rueidis already keep trying to reconnect to redis automatically if network errors.

In short, I hope that every request can be completed as soon as possible.Even if there is a network error, the result will be given as soon as possible.Both retry and timeout mechanisms cause unnecessary time loss.

**Comment by rueian** [comment]
Hi @xiluoxi,

You can now disable retrying on read-only commands via setting `DisableRetry` on the `rueidis.ClientOption` in the new v0.0.69.

**Comment by xiluoxi** [comment]
> Hi @xiluoxi,
> 
> You can now disable retrying on read-only commands via setting `DisableRetry` on the `rueidis.ClientOption` in the new v0.0.69.

thanks
