### ISSUE TITLE
Make `RedisResult`.`AsMap`/`ToMap` return `map[string]*RedisMessage`

### ISSUE THREAD

**Issue by zhiburt** [rueian/rueidis#81]
Hi,

I am not sure if it's critical to return a pointer or not.
But I am sure that it could work better with methods on `*RedisMessage`.

```go
// We would able to do this
values, _ := resp.AsMap()
m, _ := values["Something"].ToString()

// Currently we can't because we can't take an address of a map value.
// So we do the following
val := values["Something"]
from, _ := val.ToString()
```

Thanks,
Take care.

**Comment by rueian** [comment]
Hi @zhiburt, Good point.

However, I think you have no choice but always do something like `val := values["Something"]` even if AsMap/ToMap returns `map[string]*RedisMessage`. Since you need to check the existence of the key anyway.

```golang
if val, ok := values["Something"]; ok {
    from, err := val.ToString()
}
```

**Comment by zhiburt** [comment]
>  Since you need to check the existence of the key anyway.

True; that it's a good practice; (but it's not always the case :sweat_smile:)

> BTW, there is also an AsStrMap method. Then you don't need to use ToString.

Good to know

**Comment by rueian** [comment]
> It's true; that it's a good practice, but it's not always the case 😅.

What is your case for example? Or would you also consider using a for loop to iterator the map?
```golang
for k, v := range values {
    v.ToString()
}
```

I would like to avoid `map[string]*RedisMessage` for these reasons:
1. It may create confusion between the key existence and golang nil value, and may end up with this kind of code:
```go
if val, ok := values["Something"]; ok {
    if val != nil {
        val.ToString()
    }
}
```
2. It may create additional GC overhead.

**Comment by zhiburt** [comment]
I meant that you sometimes skip the check if the value exists in the map,
Yes it will panic but sometimes you don't care.

I guess you're right overall.

I must sorry for bothering you.
Take care.

**Comment by zhiburt** [comment]
> It may create additional GC overhead.

But copying large maps is no better ?:)
*I am not a golang expert
