### ISSUE TITLE
Not exit when the ctx cancel for stream read

### ISSUE THREAD

**Issue by lenonqing** [rueian/rueidis#84]
```

ctx1, cancel := context.WithCancel(ctx)
go func() {
	time.Sleep(3 * time.Second)
	cancel()
}()

xReadGroup = c.XReadGroup(ctx1, XReadGroupArgs{
	Group:    "group",
	Consumer: "consumer",
	Streams:  []string{key, ">"},
	Count:    1,
	Block:    0,
})
```

**Comment by rueian** [comment]
> ctx1, cancel := context.WithCancel(ctx)
> go func() {
> 	time.Sleep(3 * time.Second)
> 	cancel()
> }()
> 
> xReadGroup = c.XReadGroup(ctx1, XReadGroupArgs{
> 	Group:    "group",
> 	Consumer: "consumer",
> 	Streams:  []string{key, ">"},
> 	Count:    1,
> 	Block:    0,
> })

Hi @lenonqing,
Currently, this behavior is intended. Please set your timeout to the Block field of XReadGroupArgs instead.

**Comment by lenonqing** [comment]
If set timeout, I need to wait for the timeout time when I want to exit.This is different from go-redis.

**Comment by rueian** [comment]
Yes, you have to set the Block field and wait, otherwise the connection will block forever and cannot be reuse.

Or yo could take a dedicated connection from `Dedicated()` and still issue an infinite block command but call `Close()` on that dedicated connection explicitly when you want to exit early.

**Comment by lenonqing** [comment]
OK,close the dedicated connection when i want to exit, good idea!Thanks!

**Comment by rueian** [comment]
> Or you could take a dedicated connection from Dedicated() and still issue an infinite block command but call Close() on that dedicated connection explicitly when you want to exit early.

Hi @lenonqing,

I have found a way to do this automatically. You can keep your original approach in the next version:
```golang
ctx1, cancel := context.WithCancel(ctx)
go func() {
	time.Sleep(3 * time.Second)
	cancel()
}()
```

**Comment by lenonqing** [comment]
OK, Thanks!

**Comment by rueian** [comment]
Hi @lenonqing, v0.0.72 is released. Please try if it works.

**Comment by lenonqing** [comment]
OK



发自我的iPhone


------------------ Original ------------------
From: Rueian ***@***.***&gt;
Date: Thu,Aug 25,2022 10:09 PM
To: rueian/rueidis ***@***.***&gt;
Cc: lenonqing ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [rueian/rueidis] Not exit when the ctx cancel for stream read(Issue #84)





 
Hi @lenonqing, v0.0.72 is released. Please try if it works.

**Comment by lenonqing** [comment]
I try it,but it don't work when read block stream.

**Comment by rueian** [comment]
Hi @lenonqing, Sorry that I missed one part that caused it still hangs. It should work now in v.0.0.73.

**Comment by lenonqing** [comment]
work good👍,Thanks!

**Comment by GiedriusS** [comment]
> 

You can also use https://pkg.go.dev/time#AfterFunc to avoid spawning a new goroutine unnecessarily.
