### ISSUE TITLE
syntax error in prefix argument

### ISSUE THREAD

**Issue by altanozlu** [rueian/rueidis#91]
currently calling `B().ClientTracking().On().Prefix("a","b")` produces `client tracking on prefix a b` which is wrong according to redis.
```
127.0.0.1:6379> client tracking on prefix mcs: dd: BCAST
(error) ERR syntax error
127.0.0.1:6379> client tracking on prefix mcs: prefix dd: BCAST
OK
```

**Comment by rueian** [comment]
Hi @altanozlu, thank you for reporting this. The command builder will be fix in the next version.

You can use `B().Arbitrary("ANY", "CMD")` in the current version instead.

**Comment by rueian** [comment]
Hi @altanozlu, you can use the following method to construct the command with v0.0.75 now:

```go
cmd := c.B().ClientTracking().On().Prefix()
for _, p := range []string{"mcs:", "dd:"} {
	cmd = cmd.Prefix(p)
}
err := c.Do(context.Background(), cmd.Bcast().Build()).Error()
```
Please note that rueidis by default enables the opt-in mode. If you send the `BCAST` command without setting `ClientOption.DisableCache` to true, you will get an `ERR You can't switch BCAST mode on/off before disabling tracking for this client, and then re-enabling it with a different mode.` from redis.

**Comment by altanozlu** [comment]
Hi @rueian, thanks for being so fast.
