### ISSUE TITLE
READONLY You can't write against a read only replica

### ISSUE THREAD

**Issue by lenonqing** [rueian/rueidis#92]
Hello @rueian ,connect aws redis cluster,
call `rueidiscompat.NewAdapter(client).FlushAll(context.Background()).Err()`,
It returns `READONLY You can't write against a read only replica` error

**Comment by rueian** [comment]
Hi @lenonqing, are you using ElasticCache for Redis? What is the spec of the cluster in AWS? What does your rueidis.ClientOption look like?

**Comment by lenonqing** [comment]
Yes, i using AWS ElasticCache, one master, one slave.
```
xxxxxxclustercfg.usw2.cache.amazonaws.com:6379> cluster nodes    
40de7ea19bd3a66ee1cfbc078c09 x.x.x.x:6379@1122 master - 0 1662113993741 1 connected 0-16383
bc55a8cd1c55e2b9f26228d5ca9 x.x.x.x:6379@1122 myself,slave 40de7ea19bd3a66ee1cfbc078c09 0 0 1 connected
```
```go
client, err := rueidis.NewClient(
   rueidis.ClientOption{
      InitAddress: []string{"xxxxxxclustercfg.usw2.cache.amazonaws.com:6379"},
      ShuffleInit: true,
   },
)
```

rueidis version is v0.0.74.

**Comment by rueian** [comment]
Hi @lenonqing, thank you for reporting this, and I have found the cause.

However, I need to take some time to think about how to deal with commands like FLUSHALL in a cluster client.

**Comment by rueian** [comment]
Hi @lenonqing,

`rueidiscompat.NewAdapter(client).FlushAll(context.Background()).Err()` should now works with ElasticCache with v0.0.76.

**Comment by lenonqing** [comment]
OK,Thanks!
