### ISSUE TITLE
Can't get value use 'SELECT' command

### ISSUE THREAD

**Issue by lenonqing** [rueian/rueidis#94]
Hi @rueian,I use some commands,but is not work ok.
```
var key = "key"
move := c.Move(ctx, key, 2)
So(move.Err(), ShouldBeNil)
So(move.Val(), ShouldBeFalse)

s := c.Set(ctx, key, "hello", 0)
So(s.Err(), ShouldBeNil)
So(s.Val(), ShouldEqual, OK)

move = c.Move(ctx, key, 2)
So(move.Err(), ShouldBeNil)
So(move.Val(), ShouldBeTrue)

g := c.Get(ctx, key)
So(g.Err(), ShouldNotBeNil)
So(IsNil(g.Err()), ShouldBeTrue)
So(g.Val(), ShouldBeEmpty)

s = c.Select(ctx, 2)
So(s.Err(), ShouldBeNil)
So(s.Val(), ShouldEqual, OK)

g = c.Get(ctx, key)
So(g.Err(), ShouldBeNil)
So(g.Val(), ShouldEqual, "hello")
```

`select 2` and `get key`, But got `redis.Nil` error.

version is `v0.0.76`, single Redis server.

**Comment by rueian** [comment]
Hi @lenonqing,

Thank you for reporting this.

However, given that a rueidis client manages multiple connections, it is almost impossible to synchronize every context of every connection after issuing a context mutation command, such as SELECT DB, while keeping high performance.

The only practical approach is mutating the connection context at the beginning, for example setting the `ClientOption.SelectDB`.

Therefore, unfortunately, I think the `c.Select()` will be removed in the future version.
