### ISSUE TITLE
rueidis doesn't expose tmp query structs in `internal/cmds`, making it hard to construct the query dynamically

### ISSUE THREAD

**Issue by m3ngyang** [rueian/rueidis#97]
for example, we don't know how many `identifier`s would be returned ahead of time and need to construct the query dynamically.

Is there any method to do this without exposing `cmds`? Thanks.

**Comment by rueian** [comment]
Hi @m3ngyang,

Could you provide an example command you want to send and which part of it should be dynamically constructed?

BTW, You always can use https://github.com/rueian/rueidis#arbitrary-command.

**Comment by m3ngyang** [comment]
I see. I can use arbitrary-command to concatenate an original query.
