### ISSUE TITLE
Feature: High-level mocking support

### ISSUE THREAD

**Issue by dokterbob** [rueian/rueidis#98]
In order to test our Redis integration, we need to be able to mock a Redis client. Please let me know which of the various options (if any) would be perferable, I might shoot a PR.

While possible with a [miniredis](https://github.com/alicebob/miniredis), this would be testing rueidis *in addition* to our integration code. As rueidis has tests of its own, this potentially increases maintenance load.

A more elegant way to test seems to be through a mock rueidis client. However, the `Client` interface depends on `internal/cmds`, which cannot be imported by external packages, preventing us from making a mock.

It seems to me there are two ways to work around this:
1. Add a mock client as a `mock` package into rueidis.
2. Move `cmds.Builder` outside of the `internal` package.
3. Replace `cmds.Builder` by an interface. 

As for the actual mock, it seems there are two available strategies:
a. A high-level mock, like Testify's one.
b. A low-level mock, as in: https://github.com/rueian/rueidis/blob/28ab1a08c9f96629aa1115a9b313230227fee0f0/pipe_test.go#L25

This issue/feature request is specific to a. as b. can already be performed through miniredis.

**Comment by rueian** [comment]
Hi @dokterbob,

There is a new `mock` package in rueidis v0.0.79.

Please check it out: https://github.com/rueian/rueidis/tree/master/mock
