### ISSUE TITLE
JSONRepository.Search() result incorrect when use sortby

### ISSUE THREAD

**Issue by lhjw9810** [rueian/rueidis#99]
example: 
`count, ret, err := f.om.Search(context.TODO(), func(search om.FtSearchIndex) om.Completed {
		return search.Query(fmt.Sprintf(`(@shopId:%d) (@courseId:%d)`, e.ShopID, e.CourseID)).Sortby("mileage").Desc().Build()
	})`
then redis return: 
`1) "2"
2) "cycle:2"
3) 1) "mileage"
   2) "20"
   3) "$"
   4) "{\"id\":\"2\",\"ver\":1,\"shopId\":\"1\",\"shopName\":\"\xe6\xb0\x91\xe9\x99\xa2\",\"version\":\"3\",\"type\":\"MEMBER\",\"state\":0,\"isLock\":true,\"orgId\":\"12345\",\"created\":\"2022-10-11T15:17:30.470042+08:00\",\"updated\":\"2022-10-11T15:17:30.470042+08:00\",\"memberSport\":{\"memberId\":\"liangheng\",\"memberName\":\"\xe6\xa2\x81\xe7\x8f\xa9\",\"avatar\":\"\",\"speed\":0,\"mileage\":20,\"previousMileage\":0,\"hiScore\":0,\"calorie\":0,\"resistance\":0,\"courseId\":\"10002\",\"shopName\":\"\xe6\xb0\x91\xe9\x99\xa2\",\"rewardNum\":1,\"bulletNum\":2,\"visitNum\":1,\"created_at\":\"2022-10-11T17:27:59.861024+08:00\",\"updated_at\":\"2022-10-11T17:27:59.861024+08:00\"}}"
4) "cycle:80"
5) 1) "mileage"
   2) "0"
   3) "$"
   4) "{\"id\":\"80\",\"ver\":6,\"shopId\":\"1\",\"shopName\":\"\xe6\xb0\x91\xe9\x99\xa2\",\"version\":\"3\",\"type\":\"COACH\",\"liveRoomId\":\"1\",\"state\":0,\"isLock\":true,\"memberSport\":{\"memberId\":\"2\",\"memberName\":\"\",\"avatar\":\"\",\"speed\":0,\"mileage\":0,\"previousMileage\":0,\"hiScore\":0,\"calorie\":0,\"resistance\":0,\"courseId\":\"10002\",\"shopName\":\"\xe6\xb0\x91\xe9\x99\xa2\",\"rewardNum\":0,\"bulletNum\":0,\"visitNum\":0,\"created_at\":\"2022-10-11T15:25:31.411999+08:00\",\"updated_at\":\"2022-10-11T15:25:31.411999+08:00\"},\"created\":\"2022-10-11T15:17:30.470042+08:00\",\"updated\":\"2022-10-11T15:17:30.470042+08:00\"}"`

and JsonRepository Search parse result is :
`func (r *JSONRepository[T]) Search(ctx context.Context, cmdFn func(search FtSearchIndex) Completed) (n int64, s []*T, err error) {
	resp, err := r.client.Do(ctx, cmdFn(r.client.B().FtSearch().Index(r.idx))).ToArray()
	if err == nil {
		n, _ = resp[0].ToInt64()
		s = make([]*T, 0, len(resp[1:])/2)
		for i := 2; i < len(resp); i += 2 {
			if kv, _ := resp[i].ToArray(); len(kv) == 2 {
				if k, _ := kv[0].ToString(); k == "$" {
					record, _ := kv[1].ToString()
					v, err := r.decode(record)
					if err != nil {
						return 0, nil, err
					}
					s = append(s, v)
				}
			}
		}
	}
	return n, s, err
}
`
 the kv len is incorrect, and miss result map

**Comment by rueian** [comment]
Hi @lhjw9810,

Thank you for reporting this bug, it will be fixed in the next release.

**Comment by rueian** [comment]
Hi @lhjw9810, the fix has been released in v0.0.80.
